/* Phase 11 — Analytics & Reports Center */
const AnalyticsCenter={
 orders:[],products:[],refunds:[],staff:null,uid:null,
 esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));},
 num(v){return Number(v||0)||0;}, money(v){return typeof money==='function'?money(this.num(v)):`৳${Math.round(this.num(v)).toLocaleString('bn-BD')}`;},
 ts(o){const v=o.createdAt||o.orderDate||o.updatedAt;return v?.seconds?v.seconds*1000:(v instanceof Date?v.getTime():(typeof v==='string'?Date.parse(v):0));},
 total(o){return this.num(o.total??o.billAmount??o.grandTotal??o.subtotal);},
 customerKey(o){return String(o.customerPhone||o.phone||o.userId||o.customerEmail||o.customerName||'guest').trim().toLowerCase();},
 async authorize(){if(!window.FB)throw new Error('Firebase সংযোগ পাওয়া যায়নি');const u=FB.auth.currentUser;if(!u)throw new Error('অনুমোদিত স্টাফ অ্যাকাউন্ট দিয়ে লগইন করুন');const s=await FB.getDoc(FB.doc(FB.db,'staff',u.uid));if(!s.exists())throw new Error('স্টাফ প্রোফাইল পাওয়া যায়নি');const d=s.data();if(!['admin','analytics_manager','finance','zone_manager'].includes(d.role))throw new Error('Analytics & Reports Center ব্যবহারের অনুমতি নেই');if(d.active===false||['inactive','suspended','resigned'].includes(d.status))throw new Error('এই অফিস ডেস্ক বর্তমানে সক্রিয় নয়');this.uid=u.uid;this.staff=d;},
 async render(){const m=document.getElementById('analyticsAuthMessage');try{await this.authorize();if(m){m.textContent='';m.className='form-msg';}if(typeof EmployeeWorkspace!=='undefined')await EmployeeWorkspace.mountCurrent('analyticsEmployeeWorkspace');await this.refresh();}catch(e){if(m){m.textContent=e.message;m.className='form-msg err';}}},
 async refresh(){try{const [os,ps,rs]=await Promise.all([FB.getDocs(FB.collection(FB.db,'orders')),FB.getDocs(FB.collection(FB.db,'products')),FB.getDocs(FB.collection(FB.db,'refund_requests')).catch(()=>null)]);this.orders=[];os.forEach(d=>this.orders.push({id:d.id,...d.data()}));this.products=[];ps.forEach(d=>this.products.push({id:d.id,...d.data()}));this.refunds=[];if(rs)rs.forEach(d=>this.refunds.push({id:d.id,...d.data()}));this.orders.sort((a,b)=>this.ts(b)-this.ts(a));this.populateBranches();this.setDefaultDates();this.renderAll();}catch(e){toast('Analytics ডেটা লোড হয়নি: '+e.message,'error');}},
 setDefaultDates(){const f=document.getElementById('analyticsFrom'),t=document.getElementById('analyticsTo');if(!f||!t||f.value||t.value)return;const now=new Date(),from=new Date(now);from.setDate(now.getDate()-29);f.value=from.toISOString().slice(0,10);t.value=now.toISOString().slice(0,10);},
 populateBranches(){const e=document.getElementById('analyticsBranch');if(!e)return;const cur=e.value,z=[...new Set(this.orders.map(o=>o.branchZone||o.branchName).filter(Boolean))].sort();e.innerHTML='<option value="">সব শাখা</option>'+z.map(x=>`<option value="${this.esc(x)}">${this.esc((window.AREA_LABELS||{})[x]||x)}</option>`).join('');e.value=cur;},
 filtered(){const f=document.getElementById('analyticsFrom')?.value,t=document.getElementById('analyticsTo')?.value,b=document.getElementById('analyticsBranch')?.value;const fm=f?new Date(f+'T00:00:00').getTime():0,tm=t?new Date(t+'T23:59:59').getTime():Infinity;return this.orders.filter(o=>{const x=this.ts(o);return (!x||(x>=fm&&x<=tm))&&(!b||(o.branchZone||o.branchName)===b);});},
 completed(list){return list.filter(o=>!['cancelled','refunded','failed'].includes(String(o.status||'').toLowerCase()));},
 renderAll(){const list=this.filtered(),good=this.completed(list),revenue=good.reduce((s,o)=>s+this.total(o),0),delivered=list.filter(o=>o.status==='delivered').length,cancelled=list.filter(o=>o.status==='cancelled').length;const customers={};good.forEach(o=>{const k=this.customerKey(o);customers[k]=(customers[k]||0)+1;});const unique=Object.keys(customers).length,repeat=Object.values(customers).filter(n=>n>1).length,repeatRate=unique?Math.round(repeat/unique*100):0;const online=good.filter(o=>!['cod','cash','cash_on_delivery'].includes(String(o.paymentMethod||o.paymentType||'cod').toLowerCase())).length,onlineShare=good.length?Math.round(online/good.length*100):0,deliveryRate=list.length?Math.round(delivered/list.length*100):0,cancelRate=list.length?Math.round(cancelled/list.length*100):0,aov=good.length?revenue/good.length:0;const refundRisk=this.refunds.filter(r=>!['rejected','completed','paid'].includes(r.status)).reduce((s,r)=>s+this.num(r.amount||r.refundAmount),0);const score=Math.max(0,Math.min(100,100-cancelRate*2-Math.min(25,refundRisk/1000)+Math.min(10,repeatRate/5)+Math.min(5,onlineShare/20)));
 const put=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};put('analyticsRevenue',this.money(revenue));put('analyticsOrders',typeof bn==='function'?bn(list.length):list.length);put('analyticsDeliveredRate',`Delivery ${deliveryRate}%`);put('analyticsAov',this.money(aov));put('analyticsRepeatRate',`${repeatRate}%`);put('analyticsCustomers',`${typeof bn==='function'?bn(unique):unique} ইউনিক কাস্টমার`);put('analyticsOnlineShare',`${onlineShare}%`);put('analyticsCancelRate',`${cancelRate}%`);put('analyticsRefundRisk',`Refund risk ${this.money(refundRisk)}`);put('analyticsHealthScore',typeof bn==='function'?bn(Math.round(score)):Math.round(score));put('analyticsHealthTitle',score>=85?'ব্যবসার স্বাস্থ্য শক্তিশালী':score>=65?'উন্নতির সুযোগসহ স্থিতিশীল':'ব্যবস্থাপনার তাৎক্ষণিক মনোযোগ প্রয়োজন');put('analyticsHealthNote',`${list.length} অর্ডার, ${deliveryRate}% ডেলিভারি সফলতা, ${repeatRate}% পুনরায় কাস্টমার এবং ${cancelRate}% বাতিল হার।`);
 this.renderPriorities({list,revenue,deliveryRate,cancelRate,repeatRate,onlineShare,refundRisk});this.renderTrend(good);this.renderBranches(good);this.renderPayments(good);this.renderProducts(good);this.renderTable();},
 renderPriorities(x){const a=[];if(x.cancelRate>10)a.push(['danger',`বাতিল হার ${x.cancelRate}%`,'অর্ডার বাতিলের কারণ ও সংশ্লিষ্ট শাখা পর্যালোচনা করুন।']);if(x.deliveryRate<75&&x.list.length)a.push(['warn',`ডেলিভারি সফলতা ${x.deliveryRate}%`,'Delivery Command Center-এর বিলম্ব ও রাইডার সক্ষমতা যাচাই করুন।']);if(x.refundRisk>0)a.push(['warn',`${this.money(x.refundRisk)} Refund liability`,'অমীমাংসিত refund request Finance ও Customer Care-এ সমন্বয় করুন।']);if(x.repeatRate<15&&x.list.length>10)a.push(['info','Repeat customer কম','কাস্টমার retention campaign ও loyalty offer চালু করুন।']);if(x.onlineShare<20&&x.list.length>10)a.push(['info','Online payment গ্রহণ কম','Digital payment incentive ও checkout communication উন্নত করুন।']);if(!a.length)a.push(['ok','কোনো গুরুতর ব্যবসায়িক ঝুঁকি নেই','বর্তমান পারফরম্যান্স ধরে রেখে growth opportunity পর্যবেক্ষণ করুন।']);document.getElementById('analyticsPriorityList').innerHTML=a.map(v=>`<div class="analytics-priority ${v[0]}"><strong>${this.esc(v[1])}</strong><p>${this.esc(v[2])}</p></div>`).join('');},
 renderTrend(list){const days={};for(let i=13;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);days[d.toISOString().slice(0,10)]=0;}list.forEach(o=>{const t=this.ts(o);if(t){const k=new Date(t).toISOString().slice(0,10);if(k in days)days[k]+=this.total(o);}});const max=Math.max(1,...Object.values(days));document.getElementById('analyticsTrendChart').innerHTML=Object.entries(days).map(([d,v])=>`<div class="analytics-bar-item"><div><span style="height:${Math.max(3,v/max*100)}%"></span></div><small>${new Date(d+'T00:00:00').toLocaleDateString('bn-BD',{day:'numeric',month:'short'})}</small><b>${this.money(v)}</b></div>`).join('');},
 ranking(hostId,entries,format){const h=document.getElementById(hostId);if(!h)return;const max=Math.max(1,...entries.map(x=>x[1]));h.innerHTML=entries.length?entries.slice(0,8).map(([k,v],i)=>`<div class="analytics-rank-row"><b>${i+1}</b><div><strong>${this.esc(k)}</strong><span><i style="width:${v/max*100}%"></i></span></div><em>${format(v)}</em></div>`).join(''):'<div class="analytics-empty">ডেটা পাওয়া যায়নি।</div>';},
 renderBranches(list){const m={};list.forEach(o=>{const k=(window.AREA_LABELS||{})[o.branchZone]||o.branchName||o.branchZone||'অনির্ধারিত';m[k]=(m[k]||0)+this.total(o);});this.ranking('analyticsBranchList',Object.entries(m).sort((a,b)=>b[1]-a[1]),v=>this.money(v));},
 renderPayments(list){const m={};list.forEach(o=>{const k=String(o.paymentMethod||o.paymentType||'COD').toUpperCase();m[k]=(m[k]||0)+this.total(o);});this.ranking('analyticsPaymentList',Object.entries(m).sort((a,b)=>b[1]-a[1]),v=>this.money(v));},
 renderProducts(list){const m={};list.forEach(o=>(o.items||o.products||[]).forEach(i=>{const k=i.name||i.productName||i.title||i.productId||'পণ্য';m[k]=(m[k]||0)+this.num(i.qty||i.quantity||1);}));this.ranking('analyticsProductList',Object.entries(m).sort((a,b)=>b[1]-a[1]),v=>`${v} ইউনিট`);},
 renderTable(){const q=(document.getElementById('analyticsSearch')?.value||'').trim().toLowerCase();let l=this.filtered();if(q)l=l.filter(o=>[o.orderNumber,o.id,o.customerName,o.customerPhone].some(v=>String(v||'').toLowerCase().includes(q)));const b=document.getElementById('analyticsOrderTable');if(!b)return;b.innerHTML=l.slice(0,200).map(o=>`<tr><td><strong>${this.esc(o.orderNumber||o.id)}</strong></td><td>${this.ts(o)?new Date(this.ts(o)).toLocaleDateString('bn-BD'):'—'}</td><td>${this.esc(o.customerName||'—')}<small>${this.esc(o.customerPhone||'')}</small></td><td>${this.esc((window.AREA_LABELS||{})[o.branchZone]||o.branchName||o.branchZone||'—')}</td><td>${this.esc(String(o.paymentMethod||o.paymentType||'COD').toUpperCase())}</td><td><span class="status-pill ${this.esc(o.status||'')}">${this.esc(o.status||'—')}</span></td><td>${this.money(this.total(o))}</td></tr>`).join('')||'<tr><td colspan="7" class="analytics-empty">এই ফিল্টারে কোনো অর্ডার নেই।</td></tr>';},
 resetFilters(){document.getElementById('analyticsFrom').value='';document.getElementById('analyticsTo').value='';document.getElementById('analyticsBranch').value='';this.setDefaultDates();this.renderAll();},
 exportCsv(){const rows=[['Order','Date','Customer','Phone','Branch','Payment','Status','Total'],...this.filtered().map(o=>[o.orderNumber||o.id,this.ts(o)?new Date(this.ts(o)).toISOString():'',o.customerName||'',o.customerPhone||'',o.branchZone||o.branchName||'',o.paymentMethod||o.paymentType||'COD',o.status||'',this.total(o)])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`analytics-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);},
 printBrief(){window.print();},async logout(){if(FB)await FB.signOut(FB.auth).catch(()=>{});Router.go('home');}
};window.AnalyticsCenter=AnalyticsCenter;