/* branch.js — Phase 17: Branch Management Office */
const BranchOffice = {
  branches:[],staff:[],orders:[],products:[],drivers:[],transfers:[],audits:[],editingId:null,
  esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));},
  bn(v){return typeof bn==='function'?bn(v):String(v);},
  uid(){return FB?.auth?.currentUser?.uid||OwnerAuth?.currentUid||'';},
  date(v){if(!v)return '—';const d=v.toDate?v.toDate():new Date(v);return isNaN(d)?'—':d.toLocaleString('bn-BD',{dateStyle:'medium',timeStyle:'short'});},
  branchKey(x){return x.branchId||x.branch||x.branchCode||x.branchZone||'';},
  async render(){if(!window.FB){toast('Firebase সংযোগ পাওয়া যায়নি','error');return;}if(typeof EmployeeWorkspace!=='undefined')EmployeeWorkspace.mountCurrent('branchEmployeeWorkspace');await this.refresh();},
  async refresh(){
    const u=document.getElementById('branchUpdated');if(u)u.textContent='লোড হচ্ছে…';
    try{
      const reads=['branches','staff','orders','products','drivers','branch_transfers','branch_audits'].map(c=>FB.getDocs(FB.collection(FB.db,c)).catch(()=>null));
      const [b,s,o,p,d,t,a]=await Promise.all(reads);
      const arr=(snap,idKey='id')=>{const z=[];snap?.forEach(x=>z.push({[idKey]:x.id,...x.data()}));return z;};
      this.branches=arr(b);this.staff=arr(s,'uid');this.orders=arr(o);this.products=arr(p);this.drivers=arr(d);this.transfers=arr(t);this.audits=arr(a);
      this.branches.sort((x,y)=>(x.name||'').localeCompare(y.name||'','bn'));
      this.renderAll();if(u)u.textContent='আপডেট: '+new Date().toLocaleTimeString('bn-BD',{hour:'2-digit',minute:'2-digit'});
    }catch(e){toast('Branch Office লোড হয়নি: '+e.message,'error');if(u)u.textContent='লোড ব্যর্থ';}
  },
  renderAll(){this.renderStats();this.renderPriority();this.renderBranches();this.renderTransfers();this.renderAudits();this.populateBranchSelects();},
  isToday(v){if(!v)return false;const d=v.toDate?v.toDate():new Date(v),n=new Date();return d.toDateString()===n.toDateString();},
  managerFor(b){return this.staff.find(s=>s.uid===b.managerUid)||this.staff.find(s=>s.employeeId===b.managerEmployeeId);},
  staffFor(b){return this.staff.filter(s=>(s.branchId||s.branchCode||s.branchZone||s.branchName)===b.id||(s.branchId||s.branchCode)===b.branchCode);},
  ordersFor(b){return this.orders.filter(o=>this.branchKey(o)===b.id||this.branchKey(o)===b.branchCode||this.branchKey(o)===b.name);},
  productsFor(b){return this.products.filter(p=>!this.branchKey(p)||this.branchKey(p)===b.id||this.branchKey(p)===b.branchCode||this.branchKey(p)===b.name);},
  driversFor(b){return this.drivers.filter(d=>this.branchKey(d)===b.id||this.branchKey(d)===b.branchCode||this.branchKey(d)===b.name);},
  metrics(b){
    const orders=this.ordersFor(b),today=orders.filter(o=>this.isToday(o.createdAt||o.orderDate)),delivered=orders.filter(o=>o.status==='delivered'),cancelled=orders.filter(o=>['cancelled','canceled'].includes(o.status)),products=this.productsFor(b),low=products.filter(p=>(+p.stock||0)<= (+p.lowStockThreshold||5)),drivers=this.driversFor(b),online=drivers.filter(d=>d.online===true||d.isOnline===true),staff=this.staffFor(b);
    const success=orders.length?Math.round(delivered.length/orders.length*100):100;
    let health=100;if(!b.managerUid)health-=18;if(b.status!=='active')health-=25;if(low.length)health-=Math.min(20,low.length*2);if(cancelled.length&&orders.length)health-=Math.min(15,Math.round(cancelled.length/orders.length*100));if(!online.length&&b.status==='active')health-=10;
    return {orders,today,delivered,cancelled,products,low,drivers,online,staff,success,health:Math.max(0,health)};
  },
  renderStats(){
    const total=this.branches.length,active=this.branches.filter(x=>x.status==='active').length,managers=this.branches.filter(x=>x.managerUid).length,staff=new Set(this.staff.filter(x=>x.branchId||x.branchCode||x.branchZone||x.branchName).map(x=>x.uid)).size,today=this.orders.filter(x=>this.isToday(x.createdAt||x.orderDate)).length;
    const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('branchStatTotal',this.bn(total));set('branchStatActive',this.bn(active));set('branchStatManagers',this.bn(managers));set('branchStatStaff',this.bn(staff));set('branchStatOrders',this.bn(today));
  },
  renderPriority(){
    const host=document.getElementById('branchPriorityDesk');if(!host)return;const noManager=this.branches.filter(x=>x.status==='active'&&!x.managerUid),lowHealth=this.branches.filter(x=>this.metrics(x).health<65),paused=this.branches.filter(x=>x.status==='paused'),pending=this.transfers.filter(x=>(x.status||'pending')==='pending');
    const items=[];if(noManager.length)items.push(`<li><strong>${this.bn(noManager.length)}টি Active Branch-এ manager নেই</strong><span>দায়িত্ব বরাদ্দ না থাকলে branch accountability অসম্পূর্ণ থাকবে।</span></li>`);if(lowHealth.length)items.push(`<li><strong>${this.bn(lowHealth.length)}টি Branch-এর Health Score কম</strong><span>Inventory, delivery ও cancellation risk যাচাই করুন।</span></li>`);if(paused.length)items.push(`<li><strong>${this.bn(paused.length)}টি Branch paused</strong><span>পুনরায় চালু বা বন্ধ করার executive সিদ্ধান্ত প্রয়োজন।</span></li>`);if(pending.length)items.push(`<li><strong>${this.bn(pending.length)}টি Transfer Request pending</strong><span>Staff, stock, asset বা cash transfer অনুমোদন করুন।</span></li>`);
    host.innerHTML=`<div><span class="office-kicker">PRIORITY DESK</span><h2>${items.length?'Branch network-এর প্রয়োজনীয় সিদ্ধান্ত':'Branch network স্বাভাবিক'}</h2></div><ul>${items.join('')||'<li><strong>কোনো জরুরি branch risk নেই</strong><span>Performance ও capacity নিয়মিত পর্যবেক্ষণ করুন।</span></li>'}</ul>`;
  },
  renderBranches(){
    const host=document.getElementById('branchCards');if(!host)return;const q=(document.getElementById('branchSearch')?.value||'').toLowerCase(),status=document.getElementById('branchStatusFilter')?.value||'';
    const list=this.branches.filter(b=>(!status||b.status===status)&&(!q||[b.name,b.branchCode,b.address,b.coverageAreas,b.managerName,this.managerFor(b)?.name].some(v=>String(v||'').toLowerCase().includes(q))));
    host.innerHTML=list.map(b=>{const m=this.metrics(b),manager=this.managerFor(b);return `<article class="branch-card">
      <div class="branch-card-head"><div><span class="branch-code">${this.esc(b.branchCode||b.id)}</span><h3>${this.esc(b.name||'Unnamed Branch')}</h3><p>${this.esc(b.address||'ঠিকানা নেই')}</p></div><span class="branch-status ${this.esc(b.status||'planned')}">${this.esc(b.status||'planned')}</span></div>
      <div class="branch-health"><div><strong>${this.bn(m.health)}</strong><span>Health Score</span></div><div class="branch-health-bar"><i style="width:${m.health}%"></i></div></div>
      <div class="branch-kpis"><div><strong>${this.bn(m.today.length)}</strong><span>আজকের Order</span></div><div><strong>${this.bn(m.low.length)}</strong><span>Low Stock</span></div><div><strong>${this.bn(m.online.length)}/${this.bn(m.drivers.length)}</strong><span>Online Rider</span></div><div><strong>${this.bn(m.success)}%</strong><span>Success</span></div></div>
      <div class="branch-manager"><span>Branch Manager</span><strong>${this.esc(manager?.name||b.managerName||'বরাদ্দ নেই')}</strong><small>${this.esc(manager?.employeeId||'')}</small></div>
      <div class="branch-meta"><span>👥 ${this.bn(m.staff.length)} Staff</span><span>📍 ${this.esc(b.coverageAreas||'Coverage নির্ধারিত নয়')}</span><span>🕘 ${this.esc(b.openTime||'—')}–${this.esc(b.closeTime||'—')}</span></div>
      <div class="branch-actions"><button onclick="BranchOffice.editBranch('${b.id}')">Edit</button><button onclick="BranchOffice.openStaffAssignment('${b.id}')">Staff</button><button onclick="BranchOffice.toggleStatus('${b.id}')">${b.status==='active'?'Pause':'Activate'}</button></div>
    </article>`}).join('')||'<p class="attendance-empty">কোনো Branch পাওয়া যায়নি।</p>';
  },
  renderTransfers(){const host=document.getElementById('branchTransferList');if(!host)return;const list=[...this.transfers].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,20);host.innerHTML=list.map(x=>`<div class="branch-list-item"><div><strong>${this.esc((x.type||'transfer').toUpperCase())} · ${this.esc(x.reference||'')}</strong><span>${this.esc(x.fromBranchName||x.fromBranchId)} → ${this.esc(x.toBranchName||x.toBranchId)}</span></div><div><small>${this.esc(x.status||'pending')}</small>${(x.status||'pending')==='pending'?`<button onclick="BranchOffice.updateTransfer('${x.id}','approved')">Approve</button><button onclick="BranchOffice.updateTransfer('${x.id}','rejected')">Reject</button>`:''}</div></div>`).join('')||'<p class="attendance-empty">কোনো transfer request নেই।</p>';},
  renderAudits(){const host=document.getElementById('branchAuditList');if(!host)return;const list=[...this.audits].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,20);host.innerHTML=list.map(x=>`<div class="branch-list-item"><div><strong>${this.esc(x.action||'Update')}</strong><span>${this.esc(x.branchName||x.branchId||'Branch')} · ${this.esc(x.details||'')}</span></div><small>${this.date(x.createdAt)}</small></div>`).join('')||'<p class="attendance-empty">এখনও audit history নেই।</p>';},
  populateBranchSelects(){const opts=this.branches.map(b=>`<option value="${this.esc(b.id)}">${this.esc(b.name||b.branchCode||b.id)}</option>`).join('');['branchTransferFrom','branchTransferTo'].forEach(id=>{const e=document.getElementById(id);if(e)e.innerHTML=opts;});},
  openModal(id){const m=document.getElementById(id);if(m){m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}},
  closeModal(id){const m=document.getElementById(id);if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow='';}},
  managerOptions(selected=''){const managers=this.staff.filter(s=>['admin','zone_manager','branch_manager','operations_manager'].includes(s.role)||/manager/i.test(s.designation||''));return `<option value="">Manager বরাদ্দ নেই</option>`+managers.map(s=>`<option value="${this.esc(s.uid)}" ${s.uid===selected?'selected':''}>${this.esc(s.name||'কর্মী')} · ${this.esc(s.employeeId||s.designation||'')}</option>`).join('');},
  openBranchForm(){this.editingId=null;document.getElementById('branchFormTitle').textContent='নতুন Branch তৈরি';['branchName','branchCode','branchPhone','branchEmail','branchAddress','branchCoverage','branchRadius','branchOpenTime','branchCloseTime','branchOrderCapacity','branchDeliveryCapacity','branchNotes'].forEach(id=>{const e=document.getElementById(id);if(e)e.value='';});document.getElementById('branchStatus').value='active';document.getElementById('branchManager').innerHTML=this.managerOptions();this.openModal('branchFormModal');},
  editBranch(id){const b=this.branches.find(x=>x.id===id);if(!b)return;this.editingId=id;document.getElementById('branchFormTitle').textContent='Branch তথ্য সম্পাদনা';const set=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v??''};set('branchName',b.name);set('branchCode',b.branchCode);set('branchStatus',b.status);document.getElementById('branchManager').innerHTML=this.managerOptions(b.managerUid||'');set('branchPhone',b.phone);set('branchEmail',b.email);set('branchAddress',b.address);set('branchCoverage',b.coverageAreas);set('branchRadius',b.deliveryRadiusKm);set('branchOpenTime',b.openTime);set('branchCloseTime',b.closeTime);set('branchOrderCapacity',b.dailyOrderCapacity);set('branchDeliveryCapacity',b.deliveryCapacity);set('branchNotes',b.notes);this.openModal('branchFormModal');},
  async audit(branch,action,details=''){const id=`${branch.id}_${Date.now()}`;await FB.setDoc(FB.doc(FB.db,'branch_audits',id),{branchId:branch.id,branchName:branch.name||'',action,details,performedBy:this.uid(),createdAt:FB.serverTimestamp()});},
  async saveBranch(){
    const g=id=>document.getElementById(id)?.value.trim()||'',name=g('branchName');if(!name){toast('Branch নাম দিন','error');return;}const id=this.editingId||`branch_${Date.now()}`,managerUid=document.getElementById('branchManager').value,manager=this.staff.find(s=>s.uid===managerUid),old=this.branches.find(x=>x.id===id),code=g('branchCode')||`GS-BR-${String(Date.now()).slice(-4)}`;
    try{const data={name,branchCode:code,status:g('branchStatus')||'active',managerUid:managerUid||'',managerName:manager?.name||'',managerEmployeeId:manager?.employeeId||'',phone:g('branchPhone'),email:g('branchEmail'),address:g('branchAddress'),coverageAreas:g('branchCoverage'),deliveryRadiusKm:+g('branchRadius')||0,openTime:g('branchOpenTime'),closeTime:g('branchCloseTime'),dailyOrderCapacity:+g('branchOrderCapacity')||0,deliveryCapacity:+g('branchDeliveryCapacity')||0,notes:g('branchNotes'),updatedBy:this.uid(),updatedAt:FB.serverTimestamp(),createdAt:old?.createdAt||FB.serverTimestamp()};await FB.setDoc(FB.doc(FB.db,'branches',id),data,{merge:true});await this.audit({id,name},old?'Branch updated':'Branch created',code);this.closeModal('branchFormModal');await this.refresh();toast('Branch সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}
  },
  async toggleStatus(id){const b=this.branches.find(x=>x.id===id);if(!b)return;const status=b.status==='active'?'paused':'active';try{await FB.setDoc(FB.doc(FB.db,'branches',id),{status,updatedBy:this.uid(),updatedAt:FB.serverTimestamp()},{merge:true});await this.audit(b,'Status changed',`${b.status} → ${status}`);await this.refresh();toast('Branch status আপডেট হয়েছে','success');}catch(e){toast(e.message,'error');}},
  openStaffAssignment(id){const b=this.branches.find(x=>x.id===id);if(!b)return;document.getElementById('branchStaffBranchId').value=id;const assigned=this.staffFor(b).map(x=>x.uid);document.getElementById('branchStaffChecklist').innerHTML=this.staff.filter(s=>s.active!==false).map(s=>`<label><input type="checkbox" value="${this.esc(s.uid)}" ${assigned.includes(s.uid)?'checked':''}><span><strong>${this.esc(s.name||'কর্মী')}</strong><small>${this.esc(s.employeeId||s.designation||s.role||'')}</small></span></label>`).join('');this.openModal('branchStaffModal');},
  async saveStaffAssignment(){const branchId=document.getElementById('branchStaffBranchId').value,b=this.branches.find(x=>x.id===branchId);if(!b)return;const selected=[...document.querySelectorAll('#branchStaffChecklist input:checked')].map(x=>x.value);try{const writes=this.staff.map(s=>{const should=selected.includes(s.uid),isHere=(s.branchId||s.branchCode||s.branchZone||s.branchName)===b.id||(s.branchId||s.branchCode)===b.branchCode;if(should)return FB.setDoc(FB.doc(FB.db,'staff',s.uid),{branchId:b.id,branchCode:b.branchCode,branchName:b.name,updatedAt:FB.serverTimestamp()},{merge:true});if(isHere)return FB.setDoc(FB.doc(FB.db,'staff',s.uid),{branchId:'',branchCode:'',branchName:'',updatedAt:FB.serverTimestamp()},{merge:true});return Promise.resolve();});await Promise.all(writes);await this.audit(b,'Staff assignment updated',`${selected.length} staff assigned`);this.closeModal('branchStaffModal');await this.refresh();toast('Staff assignment সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}},
  openTransferForm(){this.populateBranchSelects();this.openModal('branchTransferModal');},
  async saveTransfer(){const fromId=document.getElementById('branchTransferFrom').value,toId=document.getElementById('branchTransferTo').value,type=document.getElementById('branchTransferType').value,reference=document.getElementById('branchTransferReference').value.trim();if(!fromId||!toId||fromId===toId){toast('দুটি আলাদা Branch নির্বাচন করুন','error');return;}const from=this.branches.find(x=>x.id===fromId),to=this.branches.find(x=>x.id===toId);try{const id=`transfer_${Date.now()}`;await FB.setDoc(FB.doc(FB.db,'branch_transfers',id),{type,reference,fromBranchId:fromId,fromBranchName:from?.name||'',toBranchId:toId,toBranchName:to?.name||'',note:document.getElementById('branchTransferNote').value.trim(),status:'pending',requestedBy:this.uid(),createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});this.closeModal('branchTransferModal');await this.refresh();toast('Transfer request তৈরি হয়েছে','success');}catch(e){toast(e.message,'error');}},
  async updateTransfer(id,status){try{await FB.setDoc(FB.doc(FB.db,'branch_transfers',id),{status,reviewedBy:this.uid(),reviewedAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()},{merge:true});await this.refresh();toast('Transfer request আপডেট হয়েছে','success');}catch(e){toast(e.message,'error');}},
  exportCsv(){const head=['Branch Code','Name','Status','Manager','Staff','Today Orders','Low Stock','Online Riders','Delivery Success','Health Score','Address','Coverage'];const rows=this.branches.map(b=>{const m=this.metrics(b),manager=this.managerFor(b);return[b.branchCode,b.name,b.status,manager?.name||b.managerName||'',m.staff.length,m.today.length,m.low.length,`${m.online.length}/${m.drivers.length}`,m.success,m.health,b.address,b.coverageAreas]});const csv=[head,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='golapi-branch-performance.csv';a.click();URL.revokeObjectURL(a.href);}
};
window.BranchOffice=BranchOffice;