/* documents.js — Phase 13: Document Management Office */
(function(){
  const TYPES={offer_letter:'Offer Letter',appointment_letter:'Appointment Letter',nda:'Non-Disclosure Agreement',salary_slip:'Salary Slip',warning_letter:'Warning Letter',experience_letter:'Experience Letter',resignation_acceptance:'Resignation Acceptance',termination_letter:'Termination Letter'};
  const state={docs:[],staff:[],currentUser:null};
  const el=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const dateValue=v=>{ if(!v)return ''; const d=v.toDate?v.toDate():new Date(v); return isNaN(d)?'':d.toLocaleDateString('bn-BD'); };
  const today=()=>new Date().toISOString().slice(0,10);
  const db=()=>window.firebaseDb||window.db;
  const api=()=>window.firebaseFirestore||window.firestoreApi||{};
  function template(type,s){ const n=s?.name||'[কর্মীর নাম]', d=s?.designation||'[পদবি]', id=s?.employeeId||'[Employee ID]'; const company='Golapi Shop Online';
    const map={
      offer_letter:`প্রিয় ${n},\n\nআপনাকে ${company}-এ ${d} পদে যোগদানের প্রস্তাব দিতে পেরে আমরা আনন্দিত। আপনার Employee ID হবে ${id}। নিয়োগের শর্তাবলি, কর্মঘণ্টা, পারিশ্রমিক ও কোম্পানির নীতিমালা নিয়োগপত্রে বিস্তারিত উল্লেখ থাকবে।\n\nআপনার সম্মতি লিখিতভাবে জানানোর অনুরোধ করা হলো।`,
      appointment_letter:`জনাব/জনাবা ${n},\n\nআপনাকে ${company}-এর ${d} পদে আনুষ্ঠানিকভাবে নিয়োগ দেওয়া হলো। Employee ID: ${id}। আপনি কোম্পানির আচরণবিধি, তথ্য-নিরাপত্তা নীতি, Dress Code এবং দায়িত্ব বণ্টন মেনে চলবেন।`,
      nda:`এই চুক্তির মাধ্যমে ${n} (${id}), ${d}, ${company}-এর গ্রাহক, ব্যবসা, প্রযুক্তি, মূল্য, সরবরাহকারী ও অভ্যন্তরীণ পরিচালনাসংক্রান্ত সকল গোপন তথ্য অনুমতি ছাড়া প্রকাশ না করার অঙ্গীকার করছেন। এই দায় কর্মকাল শেষ হওয়ার পরও বহাল থাকবে।`,
      salary_slip:`কর্মীর নাম: ${n}\nEmployee ID: ${id}\nপদবি: ${d}\n\nমূল বেতন: ৳0\nভাতা: ৳0\nবোনাস/ইনসেনটিভ: ৳0\nকর্তন: ৳0\nনিট পরিশোধ: ৳0`,
      warning_letter:`জনাব/জনাবা ${n},\n\nআপনার দায়িত্ব পালনে চিহ্নিত অনিয়ম/অবহেলার বিষয়ে এই আনুষ্ঠানিক সতর্কীকরণপত্র প্রদান করা হলো। নির্ধারিত সময়ের মধ্যে ব্যাখ্যা ও সংশোধনমূলক পদক্ষেপ জমা দিন। পুনরাবৃত্তি হলে কোম্পানির নীতিমালা অনুযায়ী ব্যবস্থা নেওয়া হবে।`,
      experience_letter:`এতদ্বারা প্রত্যয়ন করা যাচ্ছে যে ${n}, Employee ID ${id}, ${company}-এ ${d} পদে দায়িত্ব পালন করেছেন। কর্মকালীন সময়ে তিনি/তিনি অর্পিত দায়িত্ব পেশাদারিত্বের সঙ্গে সম্পন্ন করেছেন। আমরা তাঁর ভবিষ্যৎ সাফল্য কামনা করি।`,
      resignation_acceptance:`জনাব/জনাবা ${n},\n\nআপনার পদত্যাগপত্র গ্রহণ করা হয়েছে। নির্ধারিত handover, সম্পদ ফেরত ও হিসাব নিষ্পত্তি সম্পন্ন হওয়ার পর আপনার কর্মসম্পর্ক আনুষ্ঠানিকভাবে সমাপ্ত হবে।`,
      termination_letter:`জনাব/জনাবা ${n},\n\nকোম্পানির সিদ্ধান্ত ও প্রযোজ্য নীতিমালা অনুযায়ী ${d} পদে আপনার নিয়োগ সমাপ্ত করা হলো। কোম্পানির সকল সম্পদ, নথি ও প্রবেশাধিকার নির্ধারিত সময়ের মধ্যে হস্তান্তর করুন।`
    }; return map[type]||'';
  }
  async function load(){ const f=api(); if(!db()||!f.collection||!f.getDocs){ state.staff=[]; state.docs=[]; return; }
    const [ss,ds]=await Promise.all([f.getDocs(f.collection(db(),'staff')),f.getDocs(f.collection(db(),'employee_documents'))]);
    state.staff=ss.docs.map(x=>({id:x.id,...x.data()})); state.docs=ds.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>String(b.createdAt?.seconds||b.createdAt||'').localeCompare(String(a.createdAt?.seconds||a.createdAt||'')));
  }
  function populateStaff(){ const select=el('docEmployee'); if(!select)return; select.innerHTML='<option value="">কর্মী নির্বাচন করুন</option>'+state.staff.map(s=>`<option value="${esc(s.id)}">${esc(s.name||s.fullName||s.email||s.id)} — ${esc(s.employeeId||'ID pending')}</option>`).join(''); }
  function metrics(){ const now=new Date(), m=now.getMonth(), y=now.getFullYear(); el('docTotal').textContent=state.docs.length.toLocaleString('bn-BD'); el('docDraft').textContent=state.docs.filter(x=>x.status==='draft').length.toLocaleString('bn-BD'); el('docIssued').textContent=state.docs.filter(x=>x.status==='issued').length.toLocaleString('bn-BD'); el('docThisMonth').textContent=state.docs.filter(x=>{const d=x.createdAt?.toDate?x.createdAt.toDate():new Date(x.createdAt||0);return d.getMonth()===m&&d.getFullYear()===y}).length.toLocaleString('bn-BD'); }
  function docNo(d){return d.documentNumber||`GS-DOC-${String(d.id||'').slice(0,8).toUpperCase()}`;}
  function renderList(){ const q=(el('docSearch')?.value||'').toLowerCase(), t=el('docTypeFilter')?.value||'all', st=el('docStatusFilter')?.value||'all'; const rows=state.docs.filter(d=>(t==='all'||d.type===t)&&(st==='all'||d.status===st)&&[d.employeeName,d.employeeId,d.subject,docNo(d)].join(' ').toLowerCase().includes(q)); const host=el('documentList'); if(!host)return; host.innerHTML=rows.length?rows.map(d=>`<article class="document-row"><div class="document-file-icon">📄</div><div class="document-main"><strong>${esc(d.subject||TYPES[d.type])}</strong><span>${esc(d.employeeName)} · ${esc(d.employeeId||'ID pending')} · ${esc(TYPES[d.type]||d.type)}</span><small>${esc(docNo(d))} · ${dateValue(d.issueDate||d.createdAt)}</small></div><span class="status-pill ${esc(d.status)}">${esc(d.status||'draft')}</span><div class="document-actions"><button class="btn tiny ghost" onclick="DocumentOffice.preview('${esc(d.id)}')">দেখুন</button><button class="btn tiny ghost" onclick="DocumentOffice.edit('${esc(d.id)}')">এডিট</button><button class="btn tiny ghost" onclick="DocumentOffice.remove('${esc(d.id)}')">মুছুন</button></div></article>`).join(''):'<div class="empty-state">কোনো ডকুমেন্ট পাওয়া যায়নি।</div>'; }
  function fillEmployee(){ const s=state.staff.find(x=>x.id===el('docEmployee').value); el('docEmployeeId').value=s?.employeeId||''; el('docDesignation').value=s?.designation||s?.role||''; }
  function applyTemplate(){ const s=state.staff.find(x=>x.id===el('docEmployee').value); const type=el('docType').value; el('docSubject').value=TYPES[type]||''; el('docBody').value=template(type,s); }
  function openComposer(){ el('documentForm').reset(); el('docEditId').value=''; el('docIssueDate').value=today(); el('docStatus').value='draft'; el('documentComposer').hidden=false; applyTemplate(); }
  function closeComposer(){el('documentComposer').hidden=true;}
  function payload(){ const s=state.staff.find(x=>x.id===el('docEmployee').value)||{}; return {employeeUid:s.id||el('docEmployee').value,employeeName:s.name||s.fullName||s.email||'',employeeId:s.employeeId||'',designation:s.designation||s.role||'',type:el('docType').value,status:el('docStatus').value,issueDate:el('docIssueDate').value,subject:el('docSubject').value.trim(),body:el('docBody').value.trim(),approver:el('docApprover').value.trim(),approverTitle:el('docApproverTitle').value.trim(),reference:el('docReference').value.trim(),updatedAt:new Date().toISOString()}; }
  async function save(e){e.preventDefault(); const f=api(), id=el('docEditId').value, p=payload(); if(!p.employeeUid)return alert('কর্মী নির্বাচন করুন'); if(!db()||!f.collection)return alert('Firebase সংযোগ পাওয়া যায়নি'); try{ if(id&&f.doc&&f.updateDoc){await f.updateDoc(f.doc(db(),'employee_documents',id),p);}else{p.createdAt=new Date().toISOString();p.documentNumber=`GS-DOC-${Date.now().toString(36).toUpperCase()}`;await f.addDoc(f.collection(db(),'employee_documents'),p);} closeComposer(); await render(); }catch(err){console.error(err);alert('ডকুমেন্ট সংরক্ষণ করা যায়নি। Firestore rules পরীক্ষা করুন।');} }
  function edit(id){const d=state.docs.find(x=>x.id===id);if(!d)return;openComposer();el('docEditId').value=id;el('docEmployee').value=d.employeeUid||'';el('docType').value=d.type;el('docStatus').value=d.status||'draft';el('docIssueDate').value=d.issueDate||today();el('docSubject').value=d.subject||'';el('docBody').value=d.body||'';el('docApprover').value=d.approver||'';el('docApproverTitle').value=d.approverTitle||'';el('docReference').value=d.reference||'';fillEmployee();}
  async function remove(id){if(!confirm('ডকুমেন্টটি স্থায়ীভাবে মুছবেন?'))return;const f=api();try{await f.deleteDoc(f.doc(db(),'employee_documents',id));await render();}catch(e){alert('মুছতে ব্যর্থ হয়েছে');}}
  function paper(d){return `<article class="official-document"><header><div><h2>Golapi Shop Online</h2><p>Official Company Document</p></div><div class="doc-number">${esc(docNo(d))}</div></header><div class="document-meta"><span>তারিখ: ${esc(d.issueDate||today())}</span><span>Employee ID: ${esc(d.employeeId||'—')}</span></div><h1>${esc(d.subject||TYPES[d.type])}</h1><div class="document-recipient"><strong>${esc(d.employeeName||'')}</strong><span>${esc(d.designation||'')}</span></div><div class="document-copy">${esc(d.body||'').replace(/\n/g,'<br>')}</div><footer><div><span>অনুমোদনকারী</span><strong>${esc(d.approver||'Authorized Signatory')}</strong><small>${esc(d.approverTitle||'Golapi Shop Online')}</small></div><div class="signature-line">স্বাক্ষর ও সিল</div></footer></article>`;}
  function preview(id){const d=state.docs.find(x=>x.id===id);if(!d)return;el('documentPrintArea').innerHTML=paper(d);el('documentPreview').hidden=false;}
  function previewCurrent(){el('documentPrintArea').innerHTML=paper({...payload(),documentNumber:'PREVIEW'});el('documentPreview').hidden=false;}
  function closePreview(){el('documentPreview').hidden=true;}
  function printPreview(){const content=el('documentPrintArea').innerHTML,w=open('','_blank');w.document.write(`<html><head><title>Official Document</title><link rel="stylesheet" href="css/components.css"></head><body class="print-document-page">${content}<script>onload=()=>print()<\/script></body></html>`);w.document.close();}
  function exportCSV(){const rows=[['Document No','Employee','Employee ID','Type','Status','Issue Date','Subject'],...state.docs.map(d=>[docNo(d),d.employeeName,d.employeeId,TYPES[d.type],d.status,d.issueDate,d.subject])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='golapi-official-documents.csv';a.click();URL.revokeObjectURL(a.href);}
  async function render(){try{await load();populateStaff();metrics();renderList();if(window.EmployeeWorkspace?.mount)EmployeeWorkspace.mount('documentWorkspaceIdentity',{workspace:'Document Management Office'});}catch(e){console.error(e);renderList();}}
  window.DocumentOffice={render,openComposer,closeComposer,fillEmployee,applyTemplate,save,edit,remove,preview,previewCurrent,closePreview,printPreview,renderList,exportCSV};
})();
