/* finance-erp.js — Phase 25 */
const FinanceERP = {
  orders:[],refunds:[],purchaseOrders:[],vendorPayments:[],accounts:[],journals:[],expenses:[],budgets:[],bankItems:[],
  esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));},
  bn(v){return typeof bn==='function'?bn(v):String(v);},
  money(v){return '৳'+Number(v||0).toLocaleString('bn-BD',{maximumFractionDigits:2});},
  uid(){return FB?.auth?.currentUser?.uid||OwnerAuth?.currentUid||'';},
  date(v){if(!v)return '—';const d=v.toDate?v.toDate():new Date(v);return isNaN(d)?'—':d.toLocaleDateString('bn-BD');},
  total(o){return Number(o.total||o.grandTotal||o.totalAmount||o.amount||0);},
  async render(){if(!window.FB){toast('Firebase সংযোগ পাওয়া যায়নি','error');return;}if(typeof EmployeeWorkspace!=='undefined')EmployeeWorkspace.mountCurrent('financeErpEmployeeWorkspace');await this.refresh();},
  async refresh(){
    const u=document.getElementById('financeErpUpdated');if(u)u.textContent='Financial data লোড হচ্ছে…';
    try{
      const names=['orders','refund_requests','purchase_orders','vendor_payments','finance_accounts','finance_journals','expense_requests','department_budgets','bank_reconciliation_items'];
      const snaps=await Promise.all(names.map(n=>FB.getDocs(FB.collection(FB.db,n)).catch(()=>null)));
      const arr=s=>{const a=[];s?.forEach(x=>a.push({id:x.id,...x.data()}));return a;};
      [this.orders,this.refunds,this.purchaseOrders,this.vendorPayments,this.accounts,this.journals,this.expenses,this.budgets,this.bankItems]=snaps.map(arr);
      this.calculate();this.renderAll();
      if(u)u.textContent='আপডেট: '+new Date().toLocaleTimeString('bn-BD',{hour:'2-digit',minute:'2-digit'});
    }catch(e){toast('Finance ERP লোড হয়নি: '+e.message,'error');if(u)u.textContent='লোড ব্যর্থ';}
  },
  calculate(){
    const delivered=this.orders.filter(o=>o.status==='delivered'),revenue=delivered.reduce((n,o)=>n+this.total(o),0);
    const approvedExpenses=this.expenses.filter(e=>['approved','paid','posted'].includes(e.status)),expense=approvedExpenses.reduce((n,e)=>n+Number(e.amount||0),0)+this.vendorPayments.reduce((n,e)=>n+Number(e.amount||0),0);
    const receivable=this.orders.filter(o=>o.status==='delivered'&&['cod','cash_on_delivery'].includes(o.paymentMethod||o.paymentType)&&!o.codSettled).reduce((n,o)=>n+this.total(o),0);
    const poValue=this.purchaseOrders.reduce((n,p)=>n+Number(p.totalCost||p.totalAmount||0),0),paid=this.vendorPayments.reduce((n,p)=>n+Number(p.amount||0),0),payable=Math.max(0,poValue-paid)+this.expenses.filter(e=>['approved','pending_payment'].includes(e.status)).reduce((n,e)=>n+Number(e.amount||0),0);
    this.metrics={revenue,expense,net:revenue-expense,receivable,payable,unreconciled:this.bankItems.filter(i=>!i.reconciled).length};
  },
  renderAll(){const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('ferpRevenue',this.money(this.metrics.revenue));set('ferpExpense',this.money(this.metrics.expense));set('ferpNet',this.money(this.metrics.net));set('ferpReceivable',this.money(this.metrics.receivable));set('ferpPayable',this.money(this.metrics.payable));set('ferpUnreconciled',this.bn(this.metrics.unreconciled));this.renderPriority();this.renderAccounts();this.renderJournals();this.renderExpenses();this.renderBudgets();this.renderBank();this.renderStatements();this.populateAccounts();},
  renderPriority(){
    const h=document.getElementById('financeErpPriority'),items=[],overBudget=this.budgets.filter(b=>this.budgetSpent(b)>Number(b.amount||0)),overdue=this.expenses.filter(e=>['approved','pending_payment'].includes(e.status)&&e.dueDate&&new Date(e.dueDate)<new Date());
    if(this.metrics.receivable>0)items.push(`<li><strong>${this.money(this.metrics.receivable)} COD/receivable outstanding</strong><span>Settlement ও collection follow-up প্রয়োজন।</span></li>`);
    if(this.metrics.payable>0)items.push(`<li><strong>${this.money(this.metrics.payable)} payable exposure</strong><span>Vendor ও approved expense payment schedule করুন।</span></li>`);
    if(overBudget.length)items.push(`<li><strong>${this.bn(overBudget.length)}টি department budget exceeded</strong><span>Additional approval ছাড়া নতুন expense বন্ধ করুন।</span></li>`);
    if(overdue.length)items.push(`<li><strong>${this.bn(overdue.length)}টি approved expense overdue</strong><span>Payment execution বা hold decision প্রয়োজন।</span></li>`);
    h.innerHTML=`<div><span class="office-kicker">FINANCE PRIORITY</span><h2>${items.length?'Financial control action প্রয়োজন':'Finance position স্বাভাবিক'}</h2></div><ul>${items.join('')||'<li><strong>কোনো critical finance alert নেই</strong><span>Ledger ও bank reconciliation নিয়মিত সম্পন্ন করুন।</span></li>'}</ul>`;
  },
  tab(name,btn){['ledger','expenses','budgets','banking','statements'].forEach(n=>{const e=document.getElementById(`ferp${n.charAt(0).toUpperCase()+n.slice(1)}Pane`);if(e)e.hidden=n!==name;});document.querySelectorAll('.finance-erp-tabs button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');},
  accountBalance(a){let bal=Number(a.openingBalance||0);this.journals.forEach(j=>{if(j.debitAccountId===a.id)bal+=Number(j.amount||0);if(j.creditAccountId===a.id)bal-=Number(j.amount||0);});return bal;},
  renderAccounts(){const h=document.getElementById('ferpAccountList');if(!h)return;h.innerHTML=this.accounts.map(a=>`<article><div><strong>${this.esc(a.code||'')} · ${this.esc(a.name||'Account')}</strong><span>${this.esc(a.type||'')}</span></div><b>${this.money(this.accountBalance(a))}</b></article>`).join('')||'<p>কোনো account নেই।</p>';},
  renderJournals(){const h=document.getElementById('ferpJournalList');if(!h)return;h.innerHTML=[...this.journals].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,30).map(j=>`<article><div><strong>${this.esc(j.reference||'Journal')}</strong><span>${this.esc(j.debitAccountName||'')} → ${this.esc(j.creditAccountName||'')}</span><p>${this.esc(j.description||'')}</p></div><div><b>${this.money(j.amount)}</b><small>${this.esc(j.entryDate||'')}</small></div></article>`).join('')||'<p>কোনো journal entry নেই।</p>';},
  renderExpenses(){const b=document.getElementById('ferpExpenseTable');if(!b)return;b.innerHTML=[...this.expenses].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(e=>`<tr><td><strong>${this.esc(e.title||'Expense')}</strong><small>${this.esc(e.category||'')}</small></td><td>${this.esc(e.department||'')}</td><td>${this.money(e.amount)}</td><td>${this.esc(e.requestedByName||e.requestedBy||'')}</td><td>${this.esc(e.status||'pending')}</td><td>${e.status==='pending'?`<button onclick="FinanceERP.updateExpense('${e.id}','approved')">Approve</button><button onclick="FinanceERP.updateExpense('${e.id}','rejected')">Reject</button>`:''}${e.status==='approved'?`<button onclick="FinanceERP.updateExpense('${e.id}','paid')">Mark Paid</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">কোনো expense request নেই।</td></tr>';},
  budgetSpent(b){return this.expenses.filter(e=>e.department===b.department&&String(e.createdAt?.toDate?e.createdAt.toDate().toISOString().slice(0,7):e.createdAt||'').startsWith(b.period||'')&&['approved','paid','posted'].includes(e.status)).reduce((n,e)=>n+Number(e.amount||0),0);},
  renderBudgets(){const h=document.getElementById('ferpBudgetGrid');if(!h)return;h.innerHTML=this.budgets.map(b=>{const spent=this.budgetSpent(b),amount=Number(b.amount||0),pct=Math.min(100,Math.round(spent/Math.max(1,amount)*100));return`<article class="${spent>amount?'over':''}"><div><strong>${this.esc(b.department||'Department')}</strong><span>${this.esc(b.period||'')}</span></div><h3>${this.money(spent)} / ${this.money(amount)}</h3><div class="finance-budget-bar"><i style="width:${pct}%"></i></div><small>${pct}% used · Owner ${this.esc(b.owner||'—')}</small></article>`}).join('')||'<p>কোনো budget নেই।</p>';},
  renderBank(){const h=document.getElementById('ferpBankList');if(!h)return;h.innerHTML=[...this.bankItems].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(i=>`<article class="${i.reconciled?'reconciled':'pending'}"><div><strong>${this.esc(i.bankAccount||'Bank')} · ${this.esc(i.description||'')}</strong><span>${this.esc(i.direction||'')} · ${this.esc(i.reference||'')}</span></div><div><b>${this.money(i.amount)}</b>${!i.reconciled?`<button onclick="FinanceERP.reconcileBank('${i.id}')">Reconcile</button>`:'<small>Reconciled</small>'}</div></article>`).join('')||'<p>কোনো bank item নেই।</p>';},
  renderStatements(){
    const revAccounts=this.accounts.filter(a=>a.type==='revenue'),expAccounts=this.accounts.filter(a=>a.type==='expense'),assets=this.accounts.filter(a=>a.type==='asset').reduce((n,a)=>n+this.accountBalance(a),0),liab=this.accounts.filter(a=>a.type==='liability').reduce((n,a)=>n+Math.abs(this.accountBalance(a)),0),equity=this.accounts.filter(a=>a.type==='equity').reduce((n,a)=>n+this.accountBalance(a),0);
    document.getElementById('ferpIncomeStatement').innerHTML=`<div class="finance-statement-row"><span>Revenue</span><strong>${this.money(this.metrics.revenue+revAccounts.reduce((n,a)=>n+Math.max(0,this.accountBalance(a)),0))}</strong></div><div class="finance-statement-row"><span>Expenses</span><strong>${this.money(this.metrics.expense+expAccounts.reduce((n,a)=>n+Math.max(0,this.accountBalance(a)),0))}</strong></div><div class="finance-statement-row total"><span>Net Profit</span><strong>${this.money(this.metrics.net)}</strong></div>`;
    document.getElementById('ferpBalanceSheet').innerHTML=`<div class="finance-statement-row"><span>Assets</span><strong>${this.money(assets)}</strong></div><div class="finance-statement-row"><span>Liabilities</span><strong>${this.money(liab)}</strong></div><div class="finance-statement-row total"><span>Equity</span><strong>${this.money(equity)}</strong></div>`;
    document.getElementById('ferpCashFlow').innerHTML=`<div class="finance-statement-row"><span>Operating Inflow</span><strong>${this.money(this.metrics.revenue)}</strong></div><div class="finance-statement-row"><span>Operating Outflow</span><strong>${this.money(this.metrics.expense)}</strong></div><div class="finance-statement-row total"><span>Net Cash Flow</span><strong>${this.money(this.metrics.net)}</strong></div>`;
  },
  populateAccounts(){const opts=this.accounts.map(a=>`<option value="${this.esc(a.id)}">${this.esc(a.code||'')} · ${this.esc(a.name||'')}</option>`).join('');['ferpDebitAccount','ferpCreditAccount'].forEach(id=>{const e=document.getElementById(id);if(e)e.innerHTML=opts;});},
  openModal(id){const m=document.getElementById(id);if(m){m.classList.add('open');m.setAttribute('aria-hidden','false');}},
  closeModal(id){const m=document.getElementById(id);if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true');}},
  openJournalForm(){this.populateAccounts();document.getElementById('ferpJournalDate').value=new Date().toISOString().slice(0,10);this.openModal('ferpJournalModal');},
  openExpenseForm(){this.openModal('ferpExpenseModal');},openAccountForm(){this.openModal('ferpAccountModal');},openBudgetForm(){this.openModal('ferpBudgetModal');},openBankItemForm(){document.getElementById('ferpBankDate').value=new Date().toISOString().slice(0,10);this.openModal('ferpBankModal');},
  async saveAccount(){const code=document.getElementById('ferpAccountCode').value.trim(),name=document.getElementById('ferpAccountName').value.trim();if(!code||!name){toast('Code ও account name দিন','error');return;}try{await FB.setDoc(FB.doc(FB.db,'finance_accounts',`account_${Date.now()}`),{code,name,type:document.getElementById('ferpAccountType').value,openingBalance:+document.getElementById('ferpAccountOpening').value||0,status:'active',createdBy:this.uid(),createdAt:FB.serverTimestamp()});this.closeModal('ferpAccountModal');await this.refresh();}catch(e){toast(e.message,'error');}},
  async saveJournal(){const debit=document.getElementById('ferpDebitAccount').value,credit=document.getElementById('ferpCreditAccount').value,amount=+document.getElementById('ferpJournalAmount').value||0,da=this.accounts.find(a=>a.id===debit),ca=this.accounts.find(a=>a.id===credit);if(!da||!ca||debit===credit||amount<=0){toast('ভিন্ন Debit/Credit account ও amount দিন','error');return;}try{await FB.setDoc(FB.doc(FB.db,'finance_journals',`journal_${Date.now()}`),{entryDate:document.getElementById('ferpJournalDate').value,reference:document.getElementById('ferpJournalReference').value.trim(),debitAccountId:debit,debitAccountName:da.name||'',creditAccountId:credit,creditAccountName:ca.name||'',amount,department:document.getElementById('ferpJournalDepartment').value.trim(),description:document.getElementById('ferpJournalDescription').value.trim(),status:'posted',postedBy:this.uid(),createdAt:FB.serverTimestamp()});this.closeModal('ferpJournalModal');await this.refresh();toast('Journal posted হয়েছে','success');}catch(e){toast(e.message,'error');}},
  async saveExpense(){const title=document.getElementById('ferpExpenseTitle').value.trim(),amount=+document.getElementById('ferpExpenseAmount').value||0;if(!title||amount<=0){toast('Expense title ও amount দিন','error');return;}try{await FB.setDoc(FB.doc(FB.db,'expense_requests',`expense_${Date.now()}`),{title,category:document.getElementById('ferpExpenseCategory').value.trim(),department:document.getElementById('ferpExpenseDepartment').value.trim(),amount,paymentMethod:document.getElementById('ferpExpenseMethod').value,dueDate:document.getElementById('ferpExpenseDue').value,reason:document.getElementById('ferpExpenseReason').value.trim(),status:'pending',requestedBy:this.uid(),createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});this.closeModal('ferpExpenseModal');await this.refresh();toast('Expense submitted হয়েছে','success');}catch(e){toast(e.message,'error');}},
  async updateExpense(id,status){try{await FB.setDoc(FB.doc(FB.db,'expense_requests',id),{status,reviewedBy:this.uid(),reviewedAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()},{merge:true});await this.refresh();}catch(e){toast(e.message,'error');}},
  async saveBudget(){const department=document.getElementById('ferpBudgetDepartment').value.trim(),period=document.getElementById('ferpBudgetPeriod').value.trim(),amount=+document.getElementById('ferpBudgetAmount').value||0;if(!department||!period||amount<=0){toast('Department, period ও amount দিন','error');return;}try{await FB.setDoc(FB.doc(FB.db,'department_budgets',`budget_${Date.now()}`),{department,period,amount,owner:document.getElementById('ferpBudgetOwner').value.trim(),notes:document.getElementById('ferpBudgetNotes').value.trim(),status:'active',createdBy:this.uid(),createdAt:FB.serverTimestamp()});this.closeModal('ferpBudgetModal');await this.refresh();}catch(e){toast(e.message,'error');}},
  async saveBankItem(){const bank=document.getElementById('ferpBankAccount').value.trim(),amount=+document.getElementById('ferpBankAmount').value||0;if(!bank||!amount){toast('Bank account ও amount দিন','error');return;}try{await FB.setDoc(FB.doc(FB.db,'bank_reconciliation_items',`bank_${Date.now()}`),{bankAccount:bank,transactionDate:document.getElementById('ferpBankDate').value,description:document.getElementById('ferpBankDescription').value.trim(),amount,direction:document.getElementById('ferpBankDirection').value,reference:document.getElementById('ferpBankReference').value.trim(),reconciled:false,createdBy:this.uid(),createdAt:FB.serverTimestamp()});this.closeModal('ferpBankModal');await this.refresh();}catch(e){toast(e.message,'error');}},
  async reconcileBank(id){try{await FB.setDoc(FB.doc(FB.db,'bank_reconciliation_items',id),{reconciled:true,reconciledBy:this.uid(),reconciledAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()},{merge:true});await this.refresh();}catch(e){toast(e.message,'error');}},
  exportLedger(){const head=['Date','Reference','Debit Account','Credit Account','Amount','Department','Description'];const rows=this.journals.map(j=>[j.entryDate,j.reference,j.debitAccountName,j.creditAccountName,j.amount,j.department,j.description]);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='golapi-general-ledger.csv';a.click();URL.revokeObjectURL(a.href);}
};
window.FinanceERP=FinanceERP;