/* hr-erp.js — Phase 24: Human Resources ERP */
const HRERP = {
  staff:[],jobs:[],candidates:[],onboarding:[],reviews:[],trainings:[],promotions:[],
  esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));},
  bn(v){return typeof bn==='function'?bn(v):String(v);},
  uid(){return FB?.auth?.currentUser?.uid||OwnerAuth?.currentUid||'';},
  date(v){if(!v)return '—';const d=v.toDate?v.toDate():new Date(v);return isNaN(d)?'—':d.toLocaleString('bn-BD',{dateStyle:'medium',timeStyle:'short'});},
  async render(){
    if(!window.FB){toast('Firebase সংযোগ পাওয়া যায়নি','error');return;}
    if(typeof EmployeeWorkspace!=='undefined')EmployeeWorkspace.mountCurrent('hrErpEmployeeWorkspace');
    await this.refresh();
  },
  async refresh(){
    const u=document.getElementById('hrErpUpdated');if(u)u.textContent='People data লোড হচ্ছে…';
    try{
      const names=['staff','job_requisitions','job_candidates','employee_onboarding','performance_reviews','training_programs','employee_promotions'];
      const snaps=await Promise.all(names.map(n=>FB.getDocs(FB.collection(FB.db,n)).catch(()=>null)));
      const arr=s=>{const a=[];s?.forEach(x=>a.push({id:x.id,...x.data()}));return a;};
      [this.staff,this.jobs,this.candidates,this.onboarding,this.reviews,this.trainings,this.promotions]=snaps.map(arr);
      this.renderAll();
      if(u)u.textContent='আপডেট: '+new Date().toLocaleTimeString('bn-BD',{hour:'2-digit',minute:'2-digit'});
    }catch(e){toast('Human Resources ERP লোড হয়নি: '+e.message,'error');if(u)u.textContent='লোড ব্যর্থ';}
  },
  activeStaff(){return this.staff.filter(s=>s.active!==false&&!['inactive','suspended','resigned'].includes(s.status));},
  probationDue(){const now=new Date(),soon=new Date(Date.now()+30*86400000);return this.staff.filter(s=>s.probationEndDate&&new Date(s.probationEndDate)<=soon&&new Date(s.probationEndDate)>=now&&!s.probationReviewed);},
  trainingDue(){return this.trainings.filter(t=>(t.status||'active')==='active'&&t.dueDate&&new Date(t.dueDate)<=new Date(Date.now()+14*86400000));},
  performanceRisk(){return this.reviews.filter(r=>(+r.overallScore||0)<60||r.recommendation==='pip');},
  renderAll(){this.renderStats();this.renderPriority();this.renderJobs();this.renderCandidates();this.renderOnboarding();this.renderPerformance();this.renderTraining();this.renderPromotions();this.populateControls();},
  renderStats(){
    const interviews=this.candidates.filter(c=>c.stage==='interview'&&c.interviewDate).length;
    const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};
    set('hrStatJobs',this.bn(this.jobs.filter(j=>!['closed','cancelled'].includes(j.status)).length));
    set('hrStatCandidates',this.bn(this.candidates.filter(c=>!['hired','rejected'].includes(c.stage)).length));
    set('hrStatInterviews',this.bn(interviews));
    set('hrStatProbation',this.bn(this.probationDue().length));
    set('hrStatTraining',this.bn(this.trainingDue().length));
    set('hrStatPerformance',this.bn(this.performanceRisk().length));
  },
  renderPriority(){
    const host=document.getElementById('hrPriorityDesk');if(!host)return;const items=[],urgent=this.jobs.filter(j=>['urgent','critical'].includes(j.priority)&&!['closed','cancelled'].includes(j.status)),interviews=this.candidates.filter(c=>c.stage==='interview'&&c.interviewDate&&new Date(c.interviewDate)<=new Date(Date.now()+3*86400000)),prob=this.probationDue(),perf=this.performanceRisk();
    if(urgent.length)items.push(`<li><strong>${this.bn(urgent.length)}টি urgent position open</strong><span>Candidate sourcing ও interview priority বাড়ান।</span></li>`);
    if(interviews.length)items.push(`<li><strong>${this.bn(interviews.length)}টি interview আগামী ৩ দিনের মধ্যে</strong><span>Panel ও candidate confirmation যাচাই করুন।</span></li>`);
    if(prob.length)items.push(`<li><strong>${this.bn(prob.length)} জনের probation review due</strong><span>Confirmation, extension অথবা exit decision প্রয়োজন।</span></li>`);
    if(perf.length)items.push(`<li><strong>${this.bn(perf.length)}টি performance risk</strong><span>Training বা Performance Improvement Plan তৈরি করুন।</span></li>`);
    host.innerHTML=`<div><span class="office-kicker">PEOPLE PRIORITY</span><h2>${items.length?'মানবসম্পদ সিদ্ধান্ত প্রয়োজন':'People operations স্বাভাবিক'}</h2></div><ul>${items.join('')||'<li><strong>কোনো জরুরি HR action নেই</strong><span>Recruitment ও development pipeline নিয়মিত পর্যবেক্ষণ করুন।</span></li>'}</ul>`;
  },
  tab(name,btn){['recruitment','onboarding','performance','training','promotion'].forEach(n=>{const e=document.getElementById(`hr${n.charAt(0).toUpperCase()+n.slice(1)}Pane`);if(e)e.hidden=n!==name;});document.querySelectorAll('.hr-erp-tabs button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');},
  renderJobs(){const h=document.getElementById('hrJobList');if(!h)return;h.innerHTML=[...this.jobs].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(j=>`<article class="${this.esc(j.priority||'normal')}"><div><strong>${this.esc(j.title||'Position')}</strong><span>${this.esc(j.department||'')} · ${this.esc(j.branch||'')} · ${this.bn(j.vacancies||1)} vacancy</span><p>${this.esc(j.summary||'')}</p></div><div><small>${this.esc(j.status||'open')}</small>${!['closed','cancelled'].includes(j.status)?`<button onclick="HRERP.closeJob('${j.id}')">Close</button>`:''}</div></article>`).join('')||'<p>কোনো job requisition নেই।</p>';},
  renderCandidates(){const h=document.getElementById('hrCandidateList');if(!h)return;const stages=['applied','screening','interview','offer','hired','rejected'];h.innerHTML=stages.map(stage=>{const list=this.candidates.filter(c=>c.stage===stage);return`<section><h3>${stage.replace('_',' ')} <span>${this.bn(list.length)}</span></h3>${list.map(c=>`<article><div><strong>${this.esc(c.name||'Candidate')}</strong><span>${this.esc(c.jobTitle||'')} · ${this.esc(c.phone||c.email||'')}</span><small>${c.interviewDate?'Interview: '+this.date(c.interviewDate):''}</small></div><select onchange="HRERP.moveCandidate('${c.id}',this.value)">${stages.map(s=>`<option value="${s}" ${s===c.stage?'selected':''}>${s}</option>`).join('')}</select></article>`).join('')||'<p>Empty</p>'}</section>`}).join('');},
  renderOnboarding(){
    const body=document.getElementById('hrOnboardingTable');if(!body)return;const hires=this.staff.filter(s=>s.joiningDate||s.status==='probation');
    body.innerHTML=hires.map(s=>{const o=this.onboarding.find(x=>x.employeeUid===(s.uid||s.id))||{},done=(o.completedItems||[]).length,total=Number(o.totalItems||8),percent=Math.round(done/Math.max(1,total)*100);return`<tr><td><strong>${this.esc(s.name||'Employee')}</strong><small>${this.esc(s.employeeId||'')}</small></td><td>${this.esc(s.joiningDate||'—')}</td><td>${percent}%</td><td>${this.esc(s.probationEndDate||'—')}</td><td>${this.esc(o.status||'pending')}</td><td><button onclick="HRERP.progressOnboarding('${s.uid||s.id}')">Update</button><button onclick="HRERP.reviewProbation('${s.uid||s.id}')">Probation</button></td></tr>`}).join('')||'<tr><td colspan="6">কোনো onboarding employee নেই।</td></tr>';
  },
  renderPerformance(){const h=document.getElementById('hrPerformanceGrid');if(!h)return;h.innerHTML=[...this.reviews].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(r=>`<article class="${(+r.overallScore||0)<60?'risk':''}"><div><strong>${this.esc(r.employeeName||'Employee')}</strong><span>${this.esc(r.reviewPeriod||'Review')}</span></div><b>${this.bn(r.overallScore||0)}</b><p>${this.esc(r.feedback||'')}</p><small>${this.esc(r.recommendation||'continue')}</small></article>`).join('')||'<p>কোনো performance review নেই।</p>';},
  renderTraining(){const h=document.getElementById('hrTrainingGrid');if(!h)return;h.innerHTML=[...this.trainings].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(t=>`<article><div><strong>${this.esc(t.title||'Training')}</strong><span>${this.esc(t.category||'')} · Due ${this.esc(t.dueDate||'—')}</span></div><p>${this.esc(t.description||'')}</p><div><small>${this.bn((t.participantUids||[]).length)} participants · ${this.esc(t.status||'active')}</small>${t.status!=='completed'?`<button onclick="HRERP.completeTraining('${t.id}')">Complete</button>`:''}</div></article>`).join('')||'<p>কোনো training program নেই।</p>';},
  renderPromotions(){const h=document.getElementById('hrPromotionList');if(!h)return;h.innerHTML=[...this.promotions].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).map(p=>`<article><div><strong>${this.esc(p.employeeName||'Employee')}</strong><span>${this.esc(p.type||'promotion')} · ${this.esc(p.oldDesignation||'')} → ${this.esc(p.newDesignation||'')}</span><p>${this.esc(p.reason||'')}</p></div><small>${this.esc(p.effectiveDate||'—')}</small></article>`).join('')||'<p>কোনো career movement নেই।</p>';},
  populateControls(){const staffOpts=this.activeStaff().map(s=>`<option value="${this.esc(s.uid||s.id)}">${this.esc(s.name||'Employee')} · ${this.esc(s.employeeId||s.designation||'')}</option>`).join('');['hrReviewEmployee','hrPromotionEmployee'].forEach(id=>{const e=document.getElementById(id);if(e)e.innerHTML=staffOpts;});const job=document.getElementById('hrCandidateJob');if(job)job.innerHTML=this.jobs.filter(j=>!['closed','cancelled'].includes(j.status)).map(j=>`<option value="${this.esc(j.id)}">${this.esc(j.title||'Position')}</option>`).join('');const part=document.getElementById('hrTrainingParticipants');if(part)part.innerHTML=this.activeStaff().map(s=>`<label><input type="checkbox" value="${this.esc(s.uid||s.id)}"><span>${this.esc(s.name||'Employee')}</span></label>`).join('');},
  openModal(id){const m=document.getElementById(id);if(m){m.classList.add('open');m.setAttribute('aria-hidden','false');}},
  closeModal(id){const m=document.getElementById(id);if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true');}},
  openJobForm(){this.openModal('hrJobModal');},openCandidateForm(){this.populateControls();this.openModal('hrCandidateModal');},openReviewForm(){this.populateControls();this.openModal('hrReviewModal');},openTrainingForm(){this.populateControls();this.openModal('hrTrainingModal');},openPromotionForm(){this.populateControls();this.openModal('hrPromotionModal');},
  async saveJob(){const title=document.getElementById('hrJobTitle').value.trim();if(!title){toast('Position title দিন','error');return;}try{await FB.setDoc(FB.doc(FB.db,'job_requisitions',`job_${Date.now()}`),{title,department:document.getElementById('hrJobDepartment').value.trim(),branch:document.getElementById('hrJobBranch').value.trim(),vacancies:+document.getElementById('hrJobVacancies').value||1,employmentType:document.getElementById('hrJobType').value,priority:document.getElementById('hrJobPriority').value,summary:document.getElementById('hrJobSummary').value.trim(),status:'open',createdBy:this.uid(),createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});this.closeModal('hrJobModal');await this.refresh();toast('Job requisition তৈরি হয়েছে','success');}catch(e){toast(e.message,'error');}},
  async closeJob(id){try{await FB.setDoc(FB.doc(FB.db,'job_requisitions',id),{status:'closed',closedAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()},{merge:true});await this.refresh();}catch(e){toast(e.message,'error');}},
  async saveCandidate(){const name=document.getElementById('hrCandidateName').value.trim(),jobId=document.getElementById('hrCandidateJob').value,j=this.jobs.find(x=>x.id===jobId);if(!name||!j){toast('Candidate ও position দিন','error');return;}try{await FB.setDoc(FB.doc(FB.db,'job_candidates',`candidate_${Date.now()}`),{name,phone:document.getElementById('hrCandidatePhone').value.trim(),email:document.getElementById('hrCandidateEmail').value.trim(),jobId,jobTitle:j.title||'',stage:document.getElementById('hrCandidateStage').value,interviewDate:document.getElementById('hrCandidateInterview').value,notes:document.getElementById('hrCandidateNotes').value.trim(),createdBy:this.uid(),createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});this.closeModal('hrCandidateModal');await this.refresh();toast('Candidate সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}},
  async moveCandidate(id,stage){try{await FB.setDoc(FB.doc(FB.db,'job_candidates',id),{stage,updatedBy:this.uid(),updatedAt:FB.serverTimestamp()},{merge:true});await this.refresh();}catch(e){toast(e.message,'error');}},
  async progressOnboarding(uid){const s=this.staff.find(x=>(x.uid||x.id)===uid);if(!s)return;const current=this.onboarding.find(x=>x.employeeUid===uid)||{},done=Math.min(Number(current.totalItems||8),Number((current.completedItems||[]).length)+1),items=Array.from({length:done},(_,i)=>`item_${i+1}`);try{await FB.setDoc(FB.doc(FB.db,'employee_onboarding',uid),{employeeUid:uid,employeeName:s.name||'',employeeId:s.employeeId||'',completedItems:items,totalItems:Number(current.totalItems||8),status:done>=Number(current.totalItems||8)?'completed':'in_progress',updatedBy:this.uid(),updatedAt:FB.serverTimestamp(),createdAt:current.createdAt||FB.serverTimestamp()},{merge:true});await this.refresh();}catch(e){toast(e.message,'error');}},
  async reviewProbation(uid){const s=this.staff.find(x=>(x.uid||x.id)===uid);if(!s)return;const decision=prompt('Probation decision লিখুন: confirmed / extended / terminated','confirmed');if(!decision)return;try{await FB.setDoc(FB.doc(FB.db,'staff',uid),{probationReviewed:true,probationDecision:decision,status:decision==='confirmed'?'active':s.status,updatedAt:FB.serverTimestamp()},{merge:true});await this.refresh();toast('Probation review সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}},
  async saveReview(){const uid=document.getElementById('hrReviewEmployee').value,s=this.staff.find(x=>(x.uid||x.id)===uid),score=+document.getElementById('hrReviewScore').value||0,attendance=+document.getElementById('hrReviewAttendance').value||0,quality=+document.getElementById('hrReviewQuality').value||0;if(!s||!score){toast('Employee ও score দিন','error');return;}const overall=Math.round((score+attendance+quality)/3);try{await FB.setDoc(FB.doc(FB.db,'performance_reviews',`review_${Date.now()}`),{employeeUid:uid,employeeName:s.name||'',employeeId:s.employeeId||'',reviewPeriod:document.getElementById('hrReviewPeriod').value.trim(),performanceScore:score,attendanceScore:attendance,qualityScore:quality,overallScore:overall,recommendation:document.getElementById('hrReviewRecommendation').value,feedback:document.getElementById('hrReviewFeedback').value.trim(),reviewedBy:this.uid(),createdAt:FB.serverTimestamp()});this.closeModal('hrReviewModal');await this.refresh();toast('Performance review সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}},
  async saveTraining(){const title=document.getElementById('hrTrainingTitle').value.trim(),participants=[...document.querySelectorAll('#hrTrainingParticipants input:checked')].map(x=>x.value);if(!title){toast('Training title দিন','error');return;}try{await FB.setDoc(FB.doc(FB.db,'training_programs',`training_${Date.now()}`),{title,category:document.getElementById('hrTrainingCategory').value.trim(),startDate:document.getElementById('hrTrainingStart').value,dueDate:document.getElementById('hrTrainingDue').value,participantUids:participants,description:document.getElementById('hrTrainingDescription').value.trim(),status:'active',createdBy:this.uid(),createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});this.closeModal('hrTrainingModal');await this.refresh();toast('Training তৈরি হয়েছে','success');}catch(e){toast(e.message,'error');}},
  async completeTraining(id){try{await FB.setDoc(FB.doc(FB.db,'training_programs',id),{status:'completed',completedAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()},{merge:true});await this.refresh();}catch(e){toast(e.message,'error');}},
  async savePromotion(){const uid=document.getElementById('hrPromotionEmployee').value,s=this.staff.find(x=>(x.uid||x.id)===uid);if(!s){toast('Employee নির্বাচন করুন','error');return;}const designation=document.getElementById('hrPromotionDesignation').value.trim(),department=document.getElementById('hrPromotionDepartment').value.trim(),salary=+document.getElementById('hrPromotionSalary').value||0,type=document.getElementById('hrPromotionType').value;try{await FB.setDoc(FB.doc(FB.db,'employee_promotions',`movement_${Date.now()}`),{employeeUid:uid,employeeName:s.name||'',employeeId:s.employeeId||'',type,oldDesignation:s.designation||'',newDesignation:designation,oldDepartment:s.department||'',newDepartment:department,effectiveDate:document.getElementById('hrPromotionDate').value,newSalary:salary,reason:document.getElementById('hrPromotionReason').value.trim(),approvedBy:this.uid(),createdAt:FB.serverTimestamp()});await FB.setDoc(FB.doc(FB.db,'staff',uid),{designation:designation||s.designation,department:department||s.department,baseSalary:salary||s.baseSalary,updatedAt:FB.serverTimestamp()},{merge:true});this.closeModal('hrPromotionModal');await this.refresh();toast('Career movement সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}}
};
window.HRERP=HRERP;