/* payroll.js — Phase 15: Payroll Office */
const PayrollOffice = {
  staff:[], attendance:[], adjustments:[], records:[], month:'', run:null,
  esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));},
  bn(v){return typeof bn==='function'?bn(v):String(v);},
  money(v){return '৳'+Number(v||0).toLocaleString('bn-BD',{maximumFractionDigits:0});},
  monthKey(){return document.getElementById('payrollMonth')?.value||new Date().toISOString().slice(0,7);},
  currentUid(){return FB?.auth?.currentUser?.uid||OwnerAuth?.currentUid||'';},
  async render(){
    if(!window.FB){toast('Firebase সংযোগ পাওয়া যায়নি','error');return;}
    const input=document.getElementById('payrollMonth');if(input&&!input.value)input.value=new Date().toISOString().slice(0,7);
    if(typeof EmployeeWorkspace!=='undefined')EmployeeWorkspace.mountCurrent('payrollEmployeeWorkspace');
    await this.refresh();
  },
  async refresh(){
    this.month=this.monthKey();const stamp=document.getElementById('payrollUpdated');if(stamp)stamp.textContent='লোড হচ্ছে…';
    try{
      const [s,a,j,p,r]=await Promise.all([
        FB.getDocs(FB.collection(FB.db,'staff')),
        FB.getDocs(FB.collection(FB.db,'attendance_records')),
        FB.getDocs(FB.collection(FB.db,'salary_adjustments')),
        FB.getDocs(FB.collection(FB.db,'payroll_records')),
        FB.getDoc(FB.doc(FB.db,'payroll_runs',this.month))
      ]);
      this.staff=[];s.forEach(x=>{const v=x.data();if(v.active!==false&&!['inactive','resigned','suspended'].includes(v.status))this.staff.push({uid:x.id,...v});});
      this.attendance=[];a.forEach(x=>{const v=x.data();if(String(v.date||'').startsWith(this.month))this.attendance.push({id:x.id,...v});});
      this.adjustments=[];j.forEach(x=>{const v=x.data();if(v.month===this.month)this.adjustments.push({id:x.id,...v});});
      this.records=[];p.forEach(x=>{const v=x.data();if(v.month===this.month)this.records.push({id:x.id,...v});});
      this.run=r.exists()?{id:r.id,...r.data()}:null;
      this.staff.sort((x,y)=>(x.name||'').localeCompare(y.name||'','bn'));
      this.renderAll();if(stamp)stamp.textContent='আপডেট: '+new Date().toLocaleTimeString('bn-BD',{hour:'2-digit',minute:'2-digit'});
    }catch(e){toast('Payroll Office লোড হয়নি: '+e.message,'error');if(stamp)stamp.textContent='লোড ব্যর্থ';}
  },
  attendanceFor(uid){return this.attendance.filter(x=>x.uid===uid);},
  workHours(r){if(!r.checkInAt||!r.checkOutAt)return 0;const a=r.checkInAt.toDate?r.checkInAt.toDate():new Date(r.checkInAt),b=r.checkOutAt.toDate?r.checkOutAt.toDate():new Date(r.checkOutAt);return Math.max(0,(b-a)/36e5);},
  calc(staff){
    const existing=this.records.find(x=>x.uid===staff.uid);if(existing)return existing;
    const base=+(staff.baseSalary||staff.salary||staff.monthlySalary||0), days=this.attendanceFor(staff.uid), present=days.filter(x=>['present','late'].includes(x.status)).length;
    const absent=days.filter(x=>x.status==='absent').length, overtimeHours=days.reduce((n,x)=>n+Math.max(0,this.workHours(x)-(+x.shiftHours||8)),0);
    const perDay=base/30, absenceDeduction=Math.round(absent*perDay), overtimeRate=+(staff.overtimeRate||Math.round(base/240)), overtimePay=Math.round(overtimeHours*overtimeRate);
    const items=this.adjustments.filter(x=>x.uid===staff.uid), allowance=items.filter(x=>['allowance','bonus','incentive'].includes(x.type)).reduce((n,x)=>n+(+x.amount||0),0), manualDeduction=items.filter(x=>x.type==='deduction').reduce((n,x)=>n+(+x.amount||0),0);
    const gross=base+allowance+overtimePay, deduction=absenceDeduction+manualDeduction, net=Math.max(0,gross-deduction);
    return {id:`${this.month}_${staff.uid}`,month:this.month,uid:staff.uid,employeeName:staff.name||'',employeeId:staff.employeeId||'',designation:staff.designation||'',baseSalary:base,allowance,overtimeHours:+overtimeHours.toFixed(2),overtimePay,absenceDays:absent,absenceDeduction,manualDeduction,totalDeduction:deduction,grossSalary:gross,netSalary:net,status:'draft',presentDays:present};
  },
  rows(){return this.staff.map(s=>({...this.calc(s),staff:s}));},
  renderAll(){this.renderStats();this.renderPriority();this.renderRegister();this.renderAdjustments();this.renderRunControl();this.populateEmployees();},
  renderStats(){const rows=this.rows(),gross=rows.reduce((n,x)=>n+(+x.grossSalary||0),0),ded=rows.reduce((n,x)=>n+(+x.totalDeduction||0),0),net=rows.reduce((n,x)=>n+(+x.netSalary||0),0),paid=rows.filter(x=>x.status==='paid');const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('payrollStatEmployees',this.bn(rows.length));set('payrollStatGross',this.money(gross));set('payrollStatDeduction',this.money(ded));set('payrollStatNet',this.money(net));set('payrollStatPaid',this.bn(paid.length));set('payrollStatPaidValue',this.money(paid.reduce((n,x)=>n+(+x.netSalary||0),0)));},
  renderPriority(){const host=document.getElementById('payrollPriorityDesk');if(!host)return;const rows=this.rows(),missing=rows.filter(x=>!x.baseSalary).length,draft=rows.filter(x=>x.status==='draft').length,hold=rows.filter(x=>x.status==='hold').length,items=[];if(missing)items.push(`<li><strong>${this.bn(missing)} জনের Base Salary নেই</strong><span>Employee profile-এ salary যোগ না করলে payroll শূন্য থাকবে।</span></li>`);if(draft)items.push(`<li><strong>${this.bn(draft)}টি Draft review প্রয়োজন</strong><span>Approve করার আগে attendance ও adjustment যাচাই করুন।</span></li>`);if(hold)items.push(`<li><strong>${this.bn(hold)}টি Payroll Hold</strong><span>Hold কারণ সমাধান না হওয়া পর্যন্ত payment দেবেন না।</span></li>`);host.innerHTML=`<div><span class="office-kicker">PRIORITY DESK</span><h2>${items.length?'এই মাসের প্রয়োজনীয় সিদ্ধান্ত':'Payroll control স্বাভাবিক'}</h2></div><ul>${items.join('')||'<li><strong>কোনো জরুরি ঝুঁকি নেই</strong><span>Payroll data review-এর জন্য প্রস্তুত।</span></li>'}</ul>`;},
  renderRegister(){const host=document.getElementById('payrollRegisterBody');if(!host)return;const q=(document.getElementById('payrollSearch')?.value||'').toLowerCase(),f=document.getElementById('payrollStatusFilter')?.value||'';const rows=this.rows().filter(x=>(!f||x.status===f)&&(!q||[x.employeeName,x.employeeId,x.designation].some(v=>String(v||'').toLowerCase().includes(q))));host.innerHTML=rows.map(x=>`<tr><td><div class="attendance-person"><img src="${this.esc(x.staff.photoURL||'icons/head_logo.webp')}" onerror="this.src='icons/head_logo.webp'"><span><strong>${this.esc(x.employeeName||'নাম নেই')}</strong><small>${this.esc(x.employeeId||x.designation||'—')}</small></span></div></td><td>${this.money(x.baseSalary)}</td><td>${this.money(x.allowance)}</td><td>${this.money(x.overtimePay)}</td><td>${this.money(x.totalDeduction)}</td><td><strong>${this.money(x.netSalary)}</strong></td><td><span class="payroll-status ${this.esc(x.status)}">${({draft:'Draft',approved:'Approved',paid:'Paid',hold:'Hold'})[x.status]||x.status}</span></td><td><div class="payroll-actions"><button onclick="PayrollOffice.showSlip('${this.esc(x.uid)}')">Slip</button>${x.status==='draft'?`<button onclick="PayrollOffice.setStatus('${this.esc(x.uid)}','approved')">Approve</button>`:''}${x.status==='approved'?`<button onclick="PayrollOffice.setStatus('${this.esc(x.uid)}','paid')">Paid</button>`:''}<button onclick="PayrollOffice.setStatus('${this.esc(x.uid)}','hold')">Hold</button></div></td></tr>`).join('')||'<tr><td colspan="8">কোনো payroll record পাওয়া যায়নি।</td></tr>';},
  renderAdjustments(){const host=document.getElementById('payrollAdjustmentList');if(!host)return;const list=[...this.adjustments].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,15);host.innerHTML=list.map(x=>`<div class="payroll-list-item"><div><strong>${this.esc(x.employeeName||'কর্মী')}</strong><span>${this.esc(x.title||x.type)} · ${this.money(x.amount)}</span></div><div><span class="payroll-adjustment-type ${this.esc(x.type)}">${x.type==='deduction'?'কর্তন':'যোগ'}</span><button onclick="PayrollOffice.deleteAdjustment('${x.id}')">×</button></div></div>`).join('')||'<p class="attendance-empty">এই মাসে কোনো adjustment নেই।</p>';},
  renderRunControl(){const host=document.getElementById('payrollRunControl');if(!host)return;const status=this.run?.status||'open';host.innerHTML=`<div class="payroll-run-badge ${status}">${status==='locked'?'Locked':status==='closed'?'Closed':'Open'}</div><h3>${this.month} Payroll Run</h3><p>${status==='open'?'Draft তৈরি ও সংশোধন করা যাবে।':status==='locked'?'Run lock করা হয়েছে; অনুমোদন ছাড়া পরিবর্তন করা উচিত নয়।':'Payroll run সম্পন্ন ও বন্ধ।'}</p><div class="payroll-run-actions"><button onclick="PayrollOffice.setRunStatus('open')">Open</button><button onclick="PayrollOffice.setRunStatus('locked')">Lock</button><button onclick="PayrollOffice.setRunStatus('closed')">Close</button></div>`;},
  populateEmployees(){const e=document.getElementById('payrollAdjustmentEmployee');if(e)e.innerHTML=this.staff.map(s=>`<option value="${this.esc(s.uid)}">${this.esc(s.name)} · ${this.esc(s.employeeId||s.designation||'')}</option>`).join('');},
  async generateDrafts(){if(this.run?.status==='closed'){toast('Closed payroll run-এ নতুন draft তৈরি করা যাবে না','error');return;}if(!confirm(`${this.month} মাসের payroll draft তৈরি/আপডেট করবেন?`))return;try{for(const s of this.staff){const x=this.calc(s);if(x.status==='paid')continue;const {staff,...payload}=x;await FB.setDoc(FB.doc(FB.db,'payroll_records',x.id),{...payload,updatedAt:FB.serverTimestamp(),createdAt:x.createdAt||FB.serverTimestamp()},{merge:true});}await FB.setDoc(FB.doc(FB.db,'payroll_runs',this.month),{month:this.month,status:this.run?.status||'open',generatedBy:this.currentUid(),generatedAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()},{merge:true});toast('Payroll drafts তৈরি হয়েছে','success');await this.refresh();}catch(e){toast(e.message,'error');}},
  async setStatus(uid,status){const x=this.rows().find(r=>r.uid===uid);if(!x)return;if(this.run?.status==='closed'){toast('Payroll run বন্ধ আছে','error');return;}if(!confirm(`${x.employeeName} এর payroll ${status} করবেন?`))return;try{const {staff,...payload}=x;await FB.setDoc(FB.doc(FB.db,'payroll_records',`${this.month}_${uid}`),{...payload,status,approvedBy:status==='approved'?this.currentUid():(x.approvedBy||''),approvedAt:status==='approved'?FB.serverTimestamp():(x.approvedAt||null),paidBy:status==='paid'?this.currentUid():(x.paidBy||''),paidAt:status==='paid'?FB.serverTimestamp():(x.paidAt||null),updatedAt:FB.serverTimestamp()},{merge:true});await this.refresh();toast('Payroll status আপডেট হয়েছে','success');}catch(e){toast(e.message,'error');}},
  openModal(id){const m=document.getElementById(id);if(m){m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}},closeModal(id){const m=document.getElementById(id);if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow='';}},
  openAdjustmentForm(){this.populateEmployees();this.openModal('payrollAdjustmentModal');},
  async saveAdjustment(){const uid=document.getElementById('payrollAdjustmentEmployee').value,type=document.getElementById('payrollAdjustmentType').value,amount=+document.getElementById('payrollAdjustmentAmount').value,title=document.getElementById('payrollAdjustmentTitle').value.trim(),note=document.getElementById('payrollAdjustmentNote').value.trim(),s=this.staff.find(x=>x.uid===uid);if(!uid||!amount||amount<0||!title){toast('কর্মী, পরিমাণ ও শিরোনাম দিন','error');return;}try{const id=`${this.month}_${uid}_${Date.now()}`;await FB.setDoc(FB.doc(FB.db,'salary_adjustments',id),{month:this.month,uid,employeeName:s?.name||'',employeeId:s?.employeeId||'',type,amount,title,note,status:'approved',createdBy:this.currentUid(),createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});this.closeModal('payrollAdjustmentModal');await this.refresh();toast('Adjustment সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}},
  async deleteAdjustment(id){if(!confirm('Adjustment মুছে ফেলবেন?'))return;try{await FB.deleteDoc(FB.doc(FB.db,'salary_adjustments',id));await this.refresh();}catch(e){toast(e.message,'error');}},
  async setRunStatus(status){if(!confirm(`Payroll run ${status} করবেন?`))return;try{await FB.setDoc(FB.doc(FB.db,'payroll_runs',this.month),{month:this.month,status,updatedBy:this.currentUid(),updatedAt:FB.serverTimestamp()},{merge:true});await this.refresh();}catch(e){toast(e.message,'error');}},
  showSlip(uid){const x=this.rows().find(r=>r.uid===uid);if(!x)return;const mount=document.getElementById('payrollSlipMount');mount.innerHTML=`<div class="official-payslip"><header><div><h2>Golapi Shop Online</h2><p>Official Salary Statement</p></div><div><strong>PAYSLIP</strong><span>${this.esc(this.month)}</span></div></header><section class="payslip-employee"><div><small>কর্মী</small><strong>${this.esc(x.employeeName)}</strong><span>${this.esc(x.employeeId||'—')}</span></div><div><small>পদবি</small><strong>${this.esc(x.designation||'—')}</strong><span>Status: ${this.esc(x.status)}</span></div></section><table><tbody><tr><td>Base Salary</td><td>${this.money(x.baseSalary)}</td></tr><tr><td>Allowance / Bonus</td><td>${this.money(x.allowance)}</td></tr><tr><td>Overtime (${this.bn(x.overtimeHours)}h)</td><td>${this.money(x.overtimePay)}</td></tr><tr><td>Absence Deduction (${this.bn(x.absenceDays)} দিন)</td><td>− ${this.money(x.absenceDeduction)}</td></tr><tr><td>Other Deduction</td><td>− ${this.money(x.manualDeduction)}</td></tr><tr class="payslip-total"><td>Net Payable</td><td>${this.money(x.netSalary)}</td></tr></tbody></table><footer><span>Generated from Golapi Company OS</span><button onclick="window.print()">Print / PDF</button></footer></div>`;this.openModal('payrollSlipModal');},
  exportCsv(){const rows=this.rows(),head=['Month','Employee ID','Employee Name','Designation','Base Salary','Allowance','Overtime Pay','Deduction','Net Salary','Status'];const csv=[head,...rows.map(x=>[this.month,x.employeeId,x.employeeName,x.designation,x.baseSalary,x.allowance,x.overtimePay,x.totalDeduction,x.netSalary,x.status])].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`golapi-payroll-${this.month}.csv`;a.click();URL.revokeObjectURL(a.href);}
};
window.PayrollOffice=PayrollOffice;
