/* procurement.js — Procurement Office */
const ProcurementDash = {
  currentUid:null,currentName:null,_staff:null,
  allowedRoles:['procurement','chief_procurement_officer','vendor_relationship_officer','admin'],
  requests:[],purchaseOrders:[],suppliers:[],products:[],rfqs:[],quotations:[],vendorPayments:[],vendorContracts:[],vendorDocuments:[],editingSupplierId:null,selectedRequestId:null,
  esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));},
  tsDate(ts){return ts?.seconds?new Date(ts.seconds*1000):null;},
  dateText(v){if(!v)return '—';const d=v?.seconds?new Date(v.seconds*1000):new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('bn-BD');},
  async login(){
    const email=document.getElementById('procEmail')?.value.trim(),pass=document.getElementById('procPassword')?.value,msg=document.getElementById('procLoginMsg');
    if(!email||!pass){msg.textContent='ইমেইল ও পাসওয়ার্ড দিন';msg.className='form-msg err';return;}
    try{
      const cred=await FB.signInWithEmailAndPassword(FB.auth,email,pass);const snap=await FB.getDoc(FB.doc(FB.db,'staff',cred.user.uid));
      if(!snap.exists()||!this.allowedRoles.includes(snap.data().role)){await FB.signOut(FB.auth).catch(()=>{});msg.textContent='এই অ্যাকাউন্ট Procurement Office-এর জন্য অনুমোদিত নয়';msg.className='form-msg err';return;}
      this.currentUid=cred.user.uid;this._staff=snap.data();this.currentName=this._staff.name||'Procurement Officer';
      if(typeof StaffChat!=='undefined')StaffChat.init(this.currentUid,this.currentName,'procurement');
      await this.render();
    }catch(e){msg.textContent='লগইন ব্যর্থ: ইমেইল বা পাসওয়ার্ড সঠিক নয়';msg.className='form-msg err';}
  },
  async _restoreSession(){
    if(this.currentUid||!window.FB||!FB.auth.currentUser)return;
    try{const snap=await FB.getDoc(FB.doc(FB.db,'staff',FB.auth.currentUser.uid));if(snap.exists()&&this.allowedRoles.includes(snap.data().role)){this.currentUid=FB.auth.currentUser.uid;this._staff=snap.data();this.currentName=this._staff.name||'Procurement Officer';if(typeof StaffChat!=='undefined')StaffChat.init(this.currentUid,this.currentName,'procurement');}}catch(e){if(typeof devWarn==='function')devWarn('procurement restore failed',e.message);}
  },
  async logout(){if(window.FB)await FB.signOut(FB.auth).catch(()=>{});this.currentUid=null;this.currentName=null;document.getElementById('procLoginBox').style.display='grid';document.getElementById('procDashBox').style.display='none';},
  async render(){
    await this._restoreSession();const login=document.getElementById('procLoginBox'),dash=document.getElementById('procDashBox');
    if(!this.currentUid){if(login)login.style.display='grid';if(dash)dash.style.display='none';return;}
    login.style.display='none';dash.style.display='block';const u=document.getElementById('procUserLabel');if(u)u.textContent=this.currentName;
    if(typeof EmployeeWorkspace!=='undefined')await EmployeeWorkspace.mountCurrent('procEmployeeWorkspace');
    await Promise.all([this.loadProducts(),this.loadRequests(),this.loadSuppliers(),this.loadPurchaseOrders(),this.loadVendorControl()]);
    this.populatePoControls();this.populateVendorControls();this.renderOverview();this.renderRequests();this.renderPurchaseOrders();this.renderSuppliers();this.renderReceiving();this.renderQuotations();this.renderVendorControl();
  },
  async refresh(){await this.render();toast('✓ Procurement Office আপডেট হয়েছে','success');},
  tab(btn,name){['overview','requests','orders','suppliers','receiving','quotations','vendorcontrol'].forEach(t=>{const el=document.getElementById('proc'+t.charAt(0).toUpperCase()+t.slice(1)+'Pane');if(el)el.style.display=t===name?'block':'none';});document.querySelectorAll('#page-procurement-dash .procurement-tabs button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');},

  async loadVendorControl(){
    const get=async name=>{try{const s=await FB.getDocs(FB.collection(FB.db,name));return s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){return[];}};
    [this.rfqs,this.quotations,this.vendorPayments,this.vendorContracts,this.vendorDocuments]=await Promise.all([
      get('quotation_requests'),get('quotation_responses'),get('vendor_payments'),get('vendor_contracts'),get('vendor_documents')
    ]);
  },
  openExtraModal(id){const m=document.getElementById(id);if(m){m.classList.add('open');document.body.style.overflow='hidden';}},
  closeExtraModal(id){const m=document.getElementById(id);if(m){m.classList.remove('open');document.body.style.overflow='';}},
  populateVendorControls(){
    const vendorOpts=this.suppliers.map(s=>`<option value="${this.esc(s.id)}">${this.esc(s.name||s.companyName||'Supplier')}</option>`).join('');
    ['procQuoteVendor','procPaymentVendor','procContractVendor','procDocumentVendor'].forEach(id=>{const e=document.getElementById(id);if(e)e.innerHTML=vendorOpts;});
    const po=document.getElementById('procPaymentPo');if(po)po.innerHTML='<option value="">General Payment</option>'+this.purchaseOrders.map(x=>`<option value="${this.esc(x.id)}">${this.esc(x.poNumber||x.id)} · ${this.esc(x.supplierName||'Supplier')}</option>`).join('');
  },
  openRfqModal(){
    const product=document.getElementById('procRfqProduct'),zone=document.getElementById('procRfqZone'),vendors=document.getElementById('procRfqVendors');
    if(product)product.innerHTML=this.products.map(x=>`<option value="${this.esc(x.id)}">${this.esc(x.name||x.title||'Product')}</option>`).join('');
    if(zone){const vals=[...new Set(this.products.map(x=>x.branchZone||x.zone||x.branch||'').filter(Boolean))];zone.innerHTML='<option value="">সব Branch</option>'+vals.map(v=>`<option value="${this.esc(v)}">${this.esc(v)}</option>`).join('');}
    if(vendors)vendors.innerHTML=this.suppliers.filter(s=>(s.status||'active')==='active').map(s=>`<label><input type="checkbox" value="${this.esc(s.id)}"><span>${this.esc(s.name||'Supplier')}</span></label>`).join('');
    const d=document.getElementById('procRfqDeadline');if(d)d.value=new Date(Date.now()+7*86400000).toISOString().slice(0,10);
    this.openExtraModal('procRfqModal');
  },
  async saveRfq(){
    const productId=document.getElementById('procRfqProduct')?.value,product=this.products.find(x=>x.id===productId),qty=Number(document.getElementById('procRfqQty')?.value||0),vendorIds=[...document.querySelectorAll('#procRfqVendors input:checked')].map(x=>x.value);
    if(!product||qty<1||vendorIds.length<1){toast('Product, quantity ও অন্তত একজন vendor নির্বাচন করুন','error');return;}
    const id=`rfq_${Date.now()}`;try{await FB.setDoc(FB.doc(FB.db,'quotation_requests',id),{rfqNumber:`RFQ-${String(Date.now()).slice(-6)}`,productId,productName:product.name||product.title||'',quantity:qty,deadline:document.getElementById('procRfqDeadline').value,branchZone:document.getElementById('procRfqZone').value,vendorIds,notes:document.getElementById('procRfqNotes').value.trim(),status:'open',createdBy:this.currentUid,createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});this.closeExtraModal('procRfqModal');await this.loadVendorControl();this.renderQuotations();toast('RFQ তৈরি হয়েছে','success');}catch(e){toast(e.message,'error');}
  },
  openQuoteModal(rfqId){
    const r=this.rfqs.find(x=>x.id===rfqId);if(!r)return;document.getElementById('procQuoteRfqId').value=rfqId;
    const allowed=this.suppliers.filter(s=>(r.vendorIds||[]).includes(s.id));document.getElementById('procQuoteVendor').innerHTML=allowed.map(s=>`<option value="${this.esc(s.id)}">${this.esc(s.name||'Supplier')}</option>`).join('');
    this.openExtraModal('procQuoteModal');
  },
  async saveQuotation(){
    const rfqId=document.getElementById('procQuoteRfqId').value,r=this.rfqs.find(x=>x.id===rfqId),vendorId=document.getElementById('procQuoteVendor').value,v=this.suppliers.find(x=>x.id===vendorId),unitPrice=Number(document.getElementById('procQuoteUnitPrice').value||0);
    if(!r||!v||unitPrice<=0){toast('Vendor ও unit price দিন','error');return;}
    const id=`quote_${Date.now()}`;try{await FB.setDoc(FB.doc(FB.db,'quotation_responses',id),{rfqId,rfqNumber:r.rfqNumber||rfqId,vendorId,vendorName:v.name||'',unitPrice,totalPrice:unitPrice*Number(r.quantity||0),deliveryDays:Number(document.getElementById('procQuoteDeliveryDays').value||0),paymentTerms:document.getElementById('procQuoteTerms').value.trim(),notes:document.getElementById('procQuoteNotes').value.trim(),status:'submitted',createdBy:this.currentUid,createdAt:FB.serverTimestamp()});this.closeExtraModal('procQuoteModal');await this.loadVendorControl();this.renderQuotations();toast('Quotation সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}
  },
  async selectQuotation(rfqId,quoteId){
    const q=this.quotations.find(x=>x.id===quoteId),r=this.rfqs.find(x=>x.id===rfqId);if(!q||!r||!confirm(`${q.vendorName}-এর quotation নির্বাচন করবেন?`))return;
    try{await FB.setDoc(FB.doc(FB.db,'quotation_requests',rfqId),{status:'awarded',selectedQuotationId:quoteId,selectedVendorId:q.vendorId,selectedVendorName:q.vendorName,selectedUnitPrice:q.unitPrice,awardedAt:FB.serverTimestamp(),awardedBy:this.currentUid,updatedAt:FB.serverTimestamp()},{merge:true});await this.loadVendorControl();this.renderQuotations();toast('Quotation winner নির্বাচন হয়েছে','success');}catch(e){toast(e.message,'error');}
  },
  renderQuotations(){
    const body=document.getElementById('procQuotationTable'),summary=document.getElementById('procQuotationSummary');if(!body)return;
    const open=this.rfqs.filter(x=>(x.status||'open')==='open').length,awarded=this.rfqs.filter(x=>x.status==='awarded').length,totalQuotes=this.quotations.length;
    if(summary)summary.innerHTML=`<article><span>Open RFQ</span><strong>${typeof bn==='function'?bn(open):open}</strong></article><article><span>Quotation</span><strong>${typeof bn==='function'?bn(totalQuotes):totalQuotes}</strong></article><article><span>Awarded</span><strong>${typeof bn==='function'?bn(awarded):awarded}</strong></article>`;
    body.innerHTML=this.rfqs.map(r=>{const qs=this.quotations.filter(q=>q.rfqId===r.id).sort((a,b)=>(+a.totalPrice||0)-(+b.totalPrice||0)),best=qs[0];return `<tr><td><strong>${this.esc(r.rfqNumber||r.id)}</strong><small>${this.dateText(r.deadline)}</small></td><td>${this.esc(r.productName||'')}</td><td>${this.esc(r.quantity||0)}</td><td>${qs.length}</td><td>${best?'৳'+Number(best.totalPrice||0).toLocaleString('bn-BD')+' · '+this.esc(best.vendorName):'—'}</td><td>${this.esc(r.status||'open')}</td><td><button onclick="ProcurementDash.openQuoteModal('${r.id}')">Quote</button>${best&&r.status!=='awarded'?`<button onclick="ProcurementDash.selectQuotation('${r.id}','${best.id}')">Select Best</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="7">কোনো RFQ নেই।</td></tr>';
  },
  openVendorPaymentModal(){this.populateVendorControls();document.getElementById('procPaymentDate').value=new Date().toISOString().slice(0,10);this.openExtraModal('procVendorPaymentModal');},
  async saveVendorPayment(){
    const vendorId=document.getElementById('procPaymentVendor').value,v=this.suppliers.find(x=>x.id===vendorId),amount=Number(document.getElementById('procPaymentAmount').value||0);if(!v||amount<=0){toast('Vendor ও payment amount দিন','error');return;}
    try{await FB.setDoc(FB.doc(FB.db,'vendor_payments',`payment_${Date.now()}`),{vendorId,vendorName:v.name||'',purchaseOrderId:document.getElementById('procPaymentPo').value,amount,method:document.getElementById('procPaymentMethod').value,reference:document.getElementById('procPaymentReference').value.trim(),paymentDate:document.getElementById('procPaymentDate').value,status:'paid',createdBy:this.currentUid,createdAt:FB.serverTimestamp()});this.closeExtraModal('procVendorPaymentModal');await this.loadVendorControl();this.renderVendorControl();toast('Vendor payment সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}
  },
  openVendorContractModal(){this.populateVendorControls();this.openExtraModal('procVendorContractModal');},
  async saveVendorContract(){
    const vendorId=document.getElementById('procContractVendor').value,v=this.suppliers.find(x=>x.id===vendorId),title=document.getElementById('procContractTitle').value.trim();if(!v||!title){toast('Vendor ও contract title দিন','error');return;}
    try{await FB.setDoc(FB.doc(FB.db,'vendor_contracts',`contract_${Date.now()}`),{vendorId,vendorName:v.name||'',title,startDate:document.getElementById('procContractStart').value,endDate:document.getElementById('procContractEnd').value,notes:document.getElementById('procContractNotes').value.trim(),status:'active',createdBy:this.currentUid,createdAt:FB.serverTimestamp()});this.closeExtraModal('procVendorContractModal');await this.loadVendorControl();this.renderVendorControl();toast('Vendor contract সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}
  },
  openVendorDocumentModal(){this.populateVendorControls();this.openExtraModal('procVendorDocumentModal');},
  async saveVendorDocument(){
    const vendorId=document.getElementById('procDocumentVendor').value,v=this.suppliers.find(x=>x.id===vendorId),type=document.getElementById('procDocumentType').value;if(!v){toast('Vendor নির্বাচন করুন','error');return;}
    try{await FB.setDoc(FB.doc(FB.db,'vendor_documents',`document_${Date.now()}`),{vendorId,vendorName:v.name||'',documentType:type,documentNumber:document.getElementById('procDocumentNumber').value.trim(),expiryDate:document.getElementById('procDocumentExpiry').value,fileUrl:document.getElementById('procDocumentUrl').value.trim(),status:'active',createdBy:this.currentUid,createdAt:FB.serverTimestamp()});this.closeExtraModal('procVendorDocumentModal');await this.loadVendorControl();this.renderVendorControl();toast('Vendor document সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}
  },
  renderVendorControl(){
    const ledger=document.getElementById('procVendorLedgerTable'),contracts=document.getElementById('procVendorContractList'),risk=document.getElementById('procVendorRiskDesk');if(!ledger)return;
    const rows=this.suppliers.map(v=>{const pos=this.purchaseOrders.filter(p=>p.supplierId===v.id||p.supplierName===v.name),poValue=pos.reduce((n,p)=>n+Number(p.totalCost||p.totalAmount||0),0),paid=this.vendorPayments.filter(x=>x.vendorId===v.id).reduce((n,x)=>n+Number(x.amount||0),0),due=Math.max(0,poValue-paid),onTime=pos.length?Math.round(pos.filter(p=>!p.expectedDelivery||p.status==='received'||p.status==='completed').length/pos.length*100):100;return {v,poValue,paid,due,onTime};}).sort((a,b)=>b.due-a.due);
    ledger.innerHTML=rows.map(x=>`<tr><td><strong>${this.esc(x.v.name||'Vendor')}</strong><small>${this.esc(x.v.phone||'')}</small></td><td>৳${x.poValue.toLocaleString('bn-BD')}</td><td>৳${x.paid.toLocaleString('bn-BD')}</td><td><strong>৳${x.due.toLocaleString('bn-BD')}</strong></td><td>${x.onTime}%</td></tr>`).join('')||'<tr><td colspan="5">কোনো vendor ledger নেই।</td></tr>';
    const today=Date.now(),soon=this.vendorContracts.filter(c=>c.endDate&&new Date(c.endDate).getTime()-today<=30*86400000&&new Date(c.endDate).getTime()>=today),expiredDocs=this.vendorDocuments.filter(d=>d.expiryDate&&new Date(d.expiryDate)<new Date());
    if(risk)risk.innerHTML=`<article><strong>${rows.filter(x=>x.due>0).length}</strong><span>Vendor Due</span></article><article><strong>${soon.length}</strong><span>Contract Expiring</span></article><article><strong>${expiredDocs.length}</strong><span>Expired Documents</span></article>`;
    const combined=[...this.vendorContracts.map(x=>({...x,kind:'Contract'})),...this.vendorDocuments.map(x=>({...x,kind:'Document'}))].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));
    contracts.innerHTML=combined.slice(0,30).map(x=>`<div class="proc-control-item"><div><strong>${this.esc(x.vendorName||'Vendor')} · ${this.esc(x.title||x.documentType||x.kind)}</strong><span>${this.esc(x.kind)} · Expiry: ${this.esc(x.endDate||x.expiryDate||'—')}</span></div><small>${this.esc(x.status||'active')}</small></div>`).join('')||'<p>কোনো contract/document নেই।</p>';
  },

  async loadProducts(){try{const s=await FB.getDocs(FB.collection(FB.db,'products'));this.products=s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){this.products=[];}},
  async loadRequests(){try{const s=await FB.getDocs(FB.query(FB.collection(FB.db,'restock_requests'),FB.orderBy('createdAt','desc'),FB.limit(200)));this.requests=s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){this.requests=[];}},
  async loadSuppliers(){try{const s=await FB.getDocs(FB.query(FB.collection(FB.db,'suppliers'),FB.orderBy('createdAt','desc'),FB.limit(200)));this.suppliers=s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){this.suppliers=[];}},
  async loadPurchaseOrders(){try{const s=await FB.getDocs(FB.query(FB.collection(FB.db,'purchase_orders'),FB.orderBy('createdAt','desc'),FB.limit(300)));this.purchaseOrders=s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){this.purchaseOrders=[];}},
  renderOverview(){
    const pending=this.requests.filter(r=>(r.status||'pending')==='pending'),approved=this.requests.filter(r=>r.status==='approved'),open=this.purchaseOrders.filter(p=>['draft','placed','partial'].includes(p.status)),activeSup=this.suppliers.filter(s=>(s.status||'active')==='active'),outstanding=open.reduce((s,p)=>s+Math.max(0,Number(p.totalCost||0)-Number(p.paidAmount||0)),0);
    const score=Math.max(0,Math.min(100,100-pending.length*4-open.filter(p=>{const d=p.expectedDelivery?new Date(p.expectedDelivery):null;return d&&d<new Date();}).length*12-this.suppliers.filter(s=>s.status==='review').length*4));
    const put=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v;};put('procStatPending',bn(pending.length));put('procStatApproved',bn(approved.length));put('procStatOpenPo',bn(open.length));put('procStatSuppliers',bn(activeSup.length));put('procStatOutstanding',money(outstanding));put('procHealthScore',bn(score));put('procHealthLabel',score>=85?'স্থিতিশীল':score>=65?'মনোযোগ প্রয়োজন':'জরুরি ব্যবস্থা প্রয়োজন');
    const priorities=[];pending.filter(r=>Number(r.stockAtRequest||0)<=0).slice(0,4).forEach(r=>priorities.push({level:'critical',title:`${r.productName||'প্রোডাক্ট'} স্টক আউট`,text:`${zoneLabel(r.zone)} — ক্রয় অনুমোদন অপেক্ষমাণ`,action:`ProcurementDash.quickApprove('${r.id}')`,label:'অনুমোদন'}));
    open.filter(p=>p.expectedDelivery&&new Date(p.expectedDelivery)<new Date()).slice(0,3).forEach(p=>priorities.push({level:'warn',title:`${p.poNumber||'PO'} ডেলিভারি বিলম্বিত`,text:p.supplierName||'সাপ্লায়ার',action:`ProcurementDash.tab(document.querySelectorAll('.procurement-tabs button')[2],'orders')`,label:'PO দেখুন'}));
    if(!activeSup.length)priorities.push({level:'warn',title:'কোনো সক্রিয় সাপ্লায়ার নেই',text:'Purchase Order তৈরি করতে অন্তত একটি সাপ্লায়ার যোগ করুন',action:'ProcurementDash.openSupplierModal()',label:'যোগ করুন'});
    const host=document.getElementById('procPriorityList');if(host)host.innerHTML=priorities.length?priorities.map(x=>`<div class="proc-priority ${x.level}"><div><strong>${this.esc(x.title)}</strong><span>${this.esc(x.text)}</span></div><button onclick="${x.action}">${x.label}</button></div>`).join(''):'<div class="proc-empty-success">✓ কোনো জরুরি Procurement action নেই</div>';
    const zones=[...new Set(this.requests.map(r=>r.zone).filter(Boolean))];const body=document.getElementById('procBranchRisk');if(body)body.innerHTML=zones.map(z=>{const rows=this.requests.filter(r=>r.zone===z),pen=rows.filter(r=>(r.status||'pending')==='pending').length,out=rows.filter(r=>Number(r.stockAtRequest||0)<=0&&(r.status||'pending')==='pending').length,risk=Math.min(100,out*35+pen*8);return `<tr><td>${this.esc(zoneLabel(z))}</td><td>${bn(pen)}</td><td>${bn(out)}</td><td><span class="proc-risk ${risk>=60?'high':risk>=25?'medium':'low'}">${bn(risk)}%</span></td></tr>`;}).join('')||'<tr><td colspan="4" class="proc-empty-cell">কোনো শাখাভিত্তিক ঝুঁকি নেই</td></tr>';
  },
  renderRequests(){
    const q=(document.getElementById('procRequestSearch')?.value||'').toLowerCase(),st=document.getElementById('procRequestStatus')?.value||'';let rows=this.requests.filter(r=>(!st||(r.status||'pending')===st)&&(!q||[r.productName,zoneLabel(r.zone),r.requestedByName].some(v=>String(v||'').toLowerCase().includes(q))));const body=document.getElementById('procRequestsTable');if(!body)return;
    body.innerHTML=rows.map(r=>{const status=r.status||'pending',suggested=Number(r.requestedQty||r.suggestedQty||(Number(r.stockAtRequest||0)<=0?20:10));return `<tr><td><strong>${this.esc(r.productName||'—')}</strong><small>${this.esc(r.requestedByName||'Inventory')}</small></td><td>${this.esc(zoneLabel(r.zone))}</td><td>${bn(r.stockAtRequest||0)}</td><td><input class="proc-qty-input" id="reqQty_${r.id}" type="number" min="1" value="${suggested}"></td><td>${formatTime(r.createdAt)}</td><td><span class="proc-status ${status}">${this.statusLabel(status)}</span></td><td><div class="proc-actions">${status==='pending'?`<button class="approve" onclick="ProcurementDash.approveRequest('${r.id}')">অনুমোদন</button><button class="reject" onclick="ProcurementDash.rejectRequest('${r.id}')">বাতিল</button>`:''}${status==='approved'?`<button onclick="ProcurementDash.createPoFromRequest('${r.id}')">PO তৈরি</button>`:''}</div></td></tr>`;}).join('')||'<tr><td colspan="7" class="proc-empty-cell">কোনো রিস্টক রিকোয়েস্ট নেই</td></tr>';
  },
  statusLabel(s){return({pending:'পেন্ডিং',approved:'অনুমোদিত',rejected:'বাতিল',ordered:'PO তৈরি',received:'গৃহীত',draft:'খসড়া',placed:'অর্ডার করা',partial:'আংশিক',cancelled:'বাতিল'})[s]||s;},
  async quickApprove(id){await this.approveRequest(id);},
  async approveRequest(id){const qty=Number(document.getElementById('reqQty_'+id)?.value||10);if(qty<1)return toast('সঠিক পরিমাণ দিন','error');try{await FB.updateDoc(FB.doc(FB.db,'restock_requests',id),{status:'approved',approvedQty:qty,approvedByUid:this.currentUid,approvedByName:this.currentName,approvedAt:FB.serverTimestamp()});await this.loadRequests();this.renderOverview();this.renderRequests();toast('✓ রিস্টক অনুমোদিত হয়েছে','success');}catch(e){toast('অনুমোদন ব্যর্থ: '+e.message,'error');}},
  async rejectRequest(id){const reason=prompt('বাতিলের কারণ লিখুন:');if(reason===null)return;try{await FB.updateDoc(FB.doc(FB.db,'restock_requests',id),{status:'rejected',rejectionReason:reason,rejectedByUid:this.currentUid,rejectedByName:this.currentName,rejectedAt:FB.serverTimestamp()});await this.loadRequests();this.renderOverview();this.renderRequests();toast('রিকোয়েস্ট বাতিল হয়েছে');}catch(e){toast(e.message,'error');}},
  populatePoControls(){const prod=document.getElementById('procPoProduct'),sup=document.getElementById('procPoSupplier'),zone=document.getElementById('procPoZone');if(prod)prod.innerHTML='<option value="">প্রোডাক্ট নির্বাচন</option>'+this.products.map(p=>`<option value="${p.id}">${this.esc(p.name)} — ${this.esc(zoneLabel(p.zone))}</option>`).join('');if(sup)sup.innerHTML='<option value="">সাপ্লায়ার নির্বাচন</option>'+this.suppliers.filter(s=>(s.status||'active')==='active').map(s=>`<option value="${s.id}">${this.esc(s.name)}</option>`).join('');if(zone)zone.innerHTML=Object.entries(window.BRANCH_INFO||{}).map(([id,b])=>`<option value="${id}">${this.esc(b.label||id)}</option>`).join('');},
  createPoFromRequest(id){const r=this.requests.find(x=>x.id===id);if(!r)return;this.selectedRequestId=id;this.openPoModal();const p=this.products.find(x=>x.id===r.productId);if(p)document.getElementById('procPoProduct').value=p.id;document.getElementById('procPoQty').value=r.approvedQty||r.requestedQty||10;if(r.zone)document.getElementById('procPoZone').value=r.zone;},
  openPoModal(){this.populatePoControls();document.getElementById('procPoModal').classList.add('open');const d=new Date();d.setDate(d.getDate()+3);document.getElementById('procPoDelivery').value=d.toISOString().slice(0,10);},closePoModal(){document.getElementById('procPoModal').classList.remove('open');this.selectedRequestId=null;},
  async savePurchaseOrder(){const productId=document.getElementById('procPoProduct').value,supplierId=document.getElementById('procPoSupplier').value,qty=Number(document.getElementById('procPoQty').value),unitCost=Number(document.getElementById('procPoUnitCost').value),expectedDelivery=document.getElementById('procPoDelivery').value,zone=document.getElementById('procPoZone').value,notes=document.getElementById('procPoNotes').value.trim();const product=this.products.find(p=>p.id===productId),supplier=this.suppliers.find(s=>s.id===supplierId);if(!product||!supplier||qty<1||unitCost<0)return toast('প্রোডাক্ট, সাপ্লায়ার, পরিমাণ ও মূল্য সঠিকভাবে দিন','error');const poNumber='GS-PO-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'-'+String(Date.now()).slice(-5);try{const ref=await FB.addDoc(FB.collection(FB.db,'purchase_orders'),{poNumber,productId,productName:product.name||'—',supplierId,supplierName:supplier.name||'—',zone:zone||product.zone||'',quantity:qty,receivedQty:0,unitCost,totalCost:qty*unitCost,paidAmount:0,expectedDelivery,notes,status:'placed',restockRequestId:this.selectedRequestId||null,createdByUid:this.currentUid,createdByName:this.currentName,createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});if(this.selectedRequestId)await FB.updateDoc(FB.doc(FB.db,'restock_requests',this.selectedRequestId),{status:'ordered',purchaseOrderId:ref.id,poNumber,orderedAt:FB.serverTimestamp()});this.closePoModal();await Promise.all([this.loadPurchaseOrders(),this.loadRequests()]);this.renderOverview();this.renderRequests();this.renderPurchaseOrders();this.renderReceiving();toast('✓ Purchase Order তৈরি হয়েছে','success');}catch(e){toast('PO তৈরি ব্যর্থ: '+e.message,'error');}},
  renderPurchaseOrders(){const q=(document.getElementById('procPoSearch')?.value||'').toLowerCase(),st=document.getElementById('procPoStatus')?.value||'';const list=this.purchaseOrders.filter(p=>(!st||p.status===st)&&(!q||[p.poNumber,p.productName,p.supplierName].some(v=>String(v||'').toLowerCase().includes(q))));const body=document.getElementById('procPoTable');if(!body)return;body.innerHTML=list.map(p=>`<tr><td><strong>${this.esc(p.poNumber||p.id)}</strong></td><td>${this.esc(p.productName||'—')}</td><td>${this.esc(p.supplierName||'—')}</td><td>${bn(p.quantity||0)}</td><td>${money(p.totalCost||0)}</td><td>${this.dateText(p.expectedDelivery)}</td><td><span class="proc-status ${p.status}">${this.statusLabel(p.status)}</span></td><td><div class="proc-actions">${['draft','placed','partial'].includes(p.status)?`<button onclick="ProcurementDash.tab(document.querySelectorAll('.procurement-tabs button')[4],'receiving')">রিসিভ</button><button class="reject" onclick="ProcurementDash.cancelPo('${p.id}')">বাতিল</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="8" class="proc-empty-cell">কোনো Purchase Order নেই</td></tr>';},
  async cancelPo(id){if(!confirm('এই Purchase Order বাতিল করবেন?'))return;try{await FB.updateDoc(FB.doc(FB.db,'purchase_orders',id),{status:'cancelled',cancelledByUid:this.currentUid,cancelledAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});await this.loadPurchaseOrders();this.renderOverview();this.renderPurchaseOrders();this.renderReceiving();}catch(e){toast(e.message,'error');}},
  openSupplierModal(id=null){this.editingSupplierId=id;const s=this.suppliers.find(x=>x.id===id)||{};document.getElementById('procSupplierModalTitle').textContent=id?'সাপ্লায়ার সম্পাদনা':'নতুন সাপ্লায়ার';['Name','Contact','Phone','Email','Address'].forEach(k=>document.getElementById('supplier'+k).value=s[k.toLowerCase()]||'');document.getElementById('supplierTerms').value=s.paymentTerms||'cod';document.getElementById('supplierStatus').value=s.status||'active';document.getElementById('supplierRating').value=String(s.rating||5);document.getElementById('procSupplierModal').classList.add('open');},closeSupplierModal(){document.getElementById('procSupplierModal').classList.remove('open');this.editingSupplierId=null;},
  async saveSupplier(){const data={name:document.getElementById('supplierName').value.trim(),contact:document.getElementById('supplierContact').value.trim(),phone:document.getElementById('supplierPhone').value.trim(),email:document.getElementById('supplierEmail').value.trim(),address:document.getElementById('supplierAddress').value.trim(),paymentTerms:document.getElementById('supplierTerms').value,status:document.getElementById('supplierStatus').value,rating:Number(document.getElementById('supplierRating').value),updatedAt:FB.serverTimestamp()};if(!data.name||!data.phone)return toast('প্রতিষ্ঠানের নাম ও মোবাইল আবশ্যক','error');try{if(this.editingSupplierId)await FB.updateDoc(FB.doc(FB.db,'suppliers',this.editingSupplierId),data);else await FB.addDoc(FB.collection(FB.db,'suppliers'),{...data,createdByUid:this.currentUid,createdByName:this.currentName,createdAt:FB.serverTimestamp()});this.closeSupplierModal();await this.loadSuppliers();this.populatePoControls();this.renderOverview();this.renderSuppliers();toast('✓ সাপ্লায়ার সংরক্ষণ হয়েছে','success');}catch(e){toast(e.message,'error');}},
  renderSuppliers(){const host=document.getElementById('procSupplierGrid');if(!host)return;host.innerHTML=this.suppliers.map(s=>`<article class="supplier-card"><div class="supplier-card-top"><div class="supplier-avatar">${this.esc((s.name||'S').slice(0,1).toUpperCase())}</div><div><span class="proc-status ${s.status||'active'}">${s.status==='review'?'পর্যালোচনা':s.status==='inactive'?'নিষ্ক্রিয়':'সক্রিয়'}</span><h3>${this.esc(s.name||'—')}</h3><p>${this.esc(s.contact||'যোগাযোগ ব্যক্তি দেওয়া হয়নি')}</p></div></div><dl><div><dt>মোবাইল</dt><dd>${this.esc(s.phone||'—')}</dd></div><div><dt>পেমেন্ট</dt><dd>${this.esc(s.paymentTerms||'cod')}</dd></div><div><dt>রেটিং</dt><dd>${'★'.repeat(Number(s.rating||0))}${'☆'.repeat(Math.max(0,5-Number(s.rating||0)))}</dd></div><div><dt>ইমেইল</dt><dd>${this.esc(s.email||'—')}</dd></div></dl><button class="btn btn-outline btn-block" onclick="ProcurementDash.openSupplierModal('${s.id}')">প্রোফাইল সম্পাদনা</button></article>`).join('')||'<div class="employee-empty">এখনো কোনো সাপ্লায়ার যোগ করা হয়নি</div>';},
  renderReceiving(){const list=this.purchaseOrders.filter(p=>['placed','partial'].includes(p.status));const body=document.getElementById('procReceivingTable');if(!body)return;body.innerHTML=list.map(p=>{const remaining=Math.max(0,Number(p.quantity||0)-Number(p.receivedQty||0));return `<tr><td>${this.esc(p.poNumber||p.id)}</td><td>${this.esc(p.productName||'—')}</td><td>${bn(p.quantity||0)}</td><td>${bn(p.receivedQty||0)}</td><td><input class="proc-qty-input" id="receiveQty_${p.id}" type="number" min="1" max="${remaining}" value="${remaining}"></td><td><input class="proc-invoice-input" id="invoice_${p.id}" placeholder="Invoice #"></td><td><button class="btn btn-gold" onclick="ProcurementDash.receivePo('${p.id}')">গ্রহণ সম্পন্ন</button></td></tr>`;}).join('')||'<tr><td colspan="7" class="proc-empty-cell">গ্রহণযোগ্য কোনো Purchase Order নেই</td></tr>';},
  async receivePo(id){const po=this.purchaseOrders.find(p=>p.id===id);if(!po)return;const qty=Number(document.getElementById('receiveQty_'+id)?.value||0),invoice=document.getElementById('invoice_'+id)?.value.trim()||'';const remaining=Math.max(0,Number(po.quantity||0)-Number(po.receivedQty||0));if(qty<1||qty>remaining)return toast('গ্রহণের পরিমাণ সঠিক নয়','error');try{const product=this.products.find(p=>p.id===po.productId);if(!product)throw new Error('প্রোডাক্ট পাওয়া যায়নি');const oldStock=Number(product.stock||0),newReceived=Number(po.receivedQty||0)+qty,newStatus=newReceived>=Number(po.quantity||0)?'received':'partial';await FB.updateDoc(FB.doc(FB.db,'products',po.productId),{stock:oldStock+qty,status:'active',updatedAt:FB.serverTimestamp()});await FB.updateDoc(FB.doc(FB.db,'purchase_orders',id),{receivedQty:newReceived,status:newStatus,lastInvoice:invoice,lastReceivedQty:qty,lastReceivedAt:FB.serverTimestamp(),receivedByUid:this.currentUid,receivedByName:this.currentName,updatedAt:FB.serverTimestamp()});await FB.addDoc(FB.collection(FB.db,'stock_logs'),{productId:po.productId,productName:po.productName,zone:po.zone||product.zone||'',oldStock,newStock:oldStock+qty,source:'purchase_order',purchaseOrderId:id,poNumber:po.poNumber,invoice,updatedByUid:this.currentUid,updatedByName:this.currentName,createdAt:FB.serverTimestamp()});await FB.addDoc(FB.collection(FB.db,'goods_receipts'),{purchaseOrderId:id,poNumber:po.poNumber,productId:po.productId,productName:po.productName,quantity:qty,invoice,receivedByUid:this.currentUid,receivedByName:this.currentName,createdAt:FB.serverTimestamp()});if(newStatus==='received'&&po.restockRequestId)await FB.updateDoc(FB.doc(FB.db,'restock_requests',po.restockRequestId),{status:'received',receivedAt:FB.serverTimestamp()});product.stock=oldStock+qty;await Promise.all([this.loadPurchaseOrders(),this.loadRequests()]);this.renderOverview();this.renderPurchaseOrders();this.renderReceiving();this.renderRequests();toast('✓ পণ্য গ্রহণ ও স্টক আপডেট সম্পন্ন','success');}catch(e){toast('পণ্য গ্রহণ ব্যর্থ: '+e.message,'error');}},
  exportCsv(){const rows=[['PO Number','Product','Supplier','Zone','Quantity','Received','Unit Cost','Total','Expected Delivery','Status'],...this.purchaseOrders.map(p=>[p.poNumber,p.productName,p.supplierName,zoneLabel(p.zone),p.quantity,p.receivedQty||0,p.unitCost,p.totalCost,p.expectedDelivery,p.status])];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='golapi-purchase-orders.csv';a.click();URL.revokeObjectURL(a.href);}
};
